export interface TemplateVars {
  company: string
  oneLiner: string
  domain: string
  accentColor: string
  bgColor: string
  /** Card / surface colour from BrandWorld. Optional; falls back to a
   *  light/dark-mode-derived tint if omitted. */
  surfaceColor?: string
  /** Body text colour from BrandWorld. Wins over the dark/light fg default. */
  textColor?: string
  fontHeading: string
  fontBody: string
  fontData?: string          // mono / numeric stack (default: JetBrains Mono)
  isDark: boolean
  totalSlides: number
  slidesHtml: string
  dotNav: string
  /** Unique deck identifier baked into the HTML for viewership tracking.
   *  The beacon script reports open / slide-view / slide-leave / close
   *  events to {trackUrl} keyed by this id. */
  deckId?: string
  /** Where to POST tracking beacons. Defaults to the SignalDeck app. */
  trackUrl?: string
  /** Space-separated style-axis classes — applied to #deck so all slides
   *  inherit. 5 axes × 3-5 values = 675 combinations per layout. */
  axisClasses?: string
}

export function deckTemplate(v: TemplateVars): string {
  const fg = v.textColor || (v.isDark ? '#eef2f7' : '#0f1d2e')
  const wire = v.isDark ? 'rgba(255,255,255,0.06)' : 'rgba(15,29,46,0.06)'
  const mist = v.isDark ? 'rgba(255,255,255,0.03)' : 'rgba(15,29,46,0.03)'
  const surface = v.surfaceColor || (v.isDark ? 'rgba(255,255,255,0.04)' : 'rgba(15,29,46,0.04)')
  const fontMono = v.fontData || 'JetBrains Mono'
  const fonts = [v.fontHeading, v.fontBody, fontMono]
    .filter(Boolean)
    .filter((f, i, a) => a.indexOf(f) === i)
    .map(f => f.replace(/ /g, '+') + ':ital,wght@0,400;0,700;0,900')
    .join('&family=')
  const total2 = String(v.totalSlides).padStart(2, '0')

  const css = [
    '*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}',
    'html,body{height:100%;overflow:hidden}',
    ':root{',
    '  --bg:' + v.bgColor + ';',
    '  --accent:' + v.accentColor + ';',
    '  --fg:' + fg + ';',
    '  --wire:' + wire + ';',
    '  --mist:' + mist + ';',
    '  --snow:' + fg + ';',
    '  --surface:' + surface + ';',
    "  --fh:'" + v.fontHeading + "',system-ui,sans-serif;",
    "  --fb:'" + v.fontBody + "',system-ui,sans-serif;",
    "  --fm:'" + fontMono + "',monospace;",
    '}',
    'body{background:var(--bg);color:var(--fg);font-family:var(--fb)}',
    '#deck{height:100vh;overflow-y:scroll;scroll-snap-type:y mandatory;scroll-behavior:smooth;-ms-overflow-style:none;scrollbar-width:none}',
    '#deck::-webkit-scrollbar{display:none}',
    '.slide{position:relative;height:100vh;scroll-snap-align:start;overflow:hidden;display:flex;align-items:center;perspective:1200px}',
    '.slide-bg{position:absolute;inset:0;background:radial-gradient(ellipse at var(--bgx,50%) var(--bgy,50%),color-mix(in srgb,var(--accent) 14%,transparent),transparent 68%)}',
    '.slide-grid{position:absolute;inset:0;background-image:linear-gradient(var(--wire) 1px,transparent 1px),linear-gradient(90deg,var(--wire) 1px,transparent 1px);background-size:64px 64px;pointer-events:none}',
    '.slide-num-bg{position:absolute;right:-.05em;bottom:-.1em;font-family:var(--fh);font-size:clamp(140px,30vw,400px);font-weight:900;color:var(--mist);line-height:1;pointer-events:none;user-select:none;letter-spacing:-.04em;z-index:1}',
    '.slide-inner{position:relative;z-index:2;padding:clamp(36px,7vw,100px);max-width:1200px;width:100%;margin:0 auto;transform-origin:center center;will-change:transform,opacity}',
    '.slide-tag{font-family:var(--fm);font-size:11px;letter-spacing:3px;text-transform:uppercase;color:var(--accent);margin-bottom:18px;opacity:0;transform:translateY(10px);transition:opacity .4s ease .1s,transform .4s ease .1s}',
    '.in-view .slide-tag{opacity:1;transform:translateY(0)}',
    '.slide-title{font-family:var(--fh);font-size:clamp(32px,6.5vw,88px);font-weight:900;line-height:.94;letter-spacing:-.02em;text-transform:uppercase;margin-bottom:22px;overflow:hidden}',
    '.slide-sub{font-size:clamp(14px,1.7vw,21px);font-weight:500;opacity:.65;margin-bottom:18px;max-width:620px;line-height:1.4}',
    '.slide-lede{font-size:clamp(14px,1.5vw,19px);line-height:1.7;max-width:580px;opacity:.72}',
    '.stat-row{display:flex;gap:14px;flex-wrap:wrap;margin-top:28px}',
    '.stat-card{background:var(--surface);border:1px solid var(--wire);border-radius:14px;padding:18px 24px;min-width:130px;opacity:0;transform:translateY(18px);transition:opacity .4s ease calc(var(--i,0) * .1s + .3s),transform .4s ease calc(var(--i,0) * .1s + .3s)}',
    '.in-view .stat-card{opacity:1;transform:translateY(0)}',
    '.stat-val{font-family:var(--fh);font-size:clamp(26px,3.8vw,48px);font-weight:900;color:var(--accent);line-height:1;margin-bottom:5px}',
    '.stat-lbl{font-family:var(--fm);font-size:10px;letter-spacing:2px;text-transform:uppercase;opacity:.45}',
    '.bullet-list{list-style:none;margin-top:24px;display:flex;flex-direction:column;gap:12px;max-width:620px}',
    '.bullet-list li{font-size:clamp(13px,1.4vw,17px);line-height:1.55;padding-left:24px;position:relative;opacity:0;transform:translateX(-14px);transition:opacity .4s ease calc(var(--i,0) * .1s + .4s),transform .4s ease calc(var(--i,0) * .1s + .4s)}',
    '.in-view .bullet-list li{opacity:1;transform:translateX(0)}',
    ".bullet-list li::before{content:'';position:absolute;left:0;top:.6em;width:10px;height:2px;background:var(--accent)}",
    '.reveal-wipe{display:inline-block;clip-path:inset(0 100% 0 0);transition:clip-path .8s cubic-bezier(.16,1,.3,1) .15s}',
    '.in-view .reveal-wipe{clip-path:inset(0 0% 0 0)}',
    '.reveal-up{opacity:0;transform:translateY(22px);transition:opacity .55s ease,transform .55s ease}',
    '.in-view .reveal-up{opacity:1;transform:translateY(0)}',
    '.d1{transition-delay:.15s!important}.d2{transition-delay:.3s!important}.d3{transition-delay:.45s!important}.d4{transition-delay:.6s!important}',
    '.slide[data-tx="zoom-passage"] .slide-inner{transform:scale(.45);opacity:0;transition:transform 1s cubic-bezier(.16,1,.3,1),opacity .6s ease}',
    '.slide[data-tx="zoom-passage"].in-view .slide-inner{transform:scale(1);opacity:1}',
    '.slide[data-tx="zoom-passage"].out-above .slide-inner{transform:scale(1.7);opacity:0}',
    '.slide[data-tx="explode"] .slide-inner{transform:scale(1.35);opacity:0;transition:transform .75s cubic-bezier(.34,1.56,.64,1),opacity .45s ease}',
    '.slide[data-tx="explode"].in-view .slide-inner{transform:scale(1);opacity:1}',
    // Per-child scatter on exit — each card flies in its own direction so
    // the signature "explode" actually explodes. nth-child(6n+1..6n+6).
    '.slide[data-tx="explode"] .tx-group{transform-style:preserve-3d}',
    '.slide[data-tx="explode"] .tx-group>*{transition:opacity .7s cubic-bezier(.76,0,.24,1),transform .9s cubic-bezier(.76,0,.24,1),filter .7s cubic-bezier(.76,0,.24,1);will-change:transform,opacity,filter}',
    '.slide[data-tx="explode"].out-above .tx-group>*:nth-child(6n+1){opacity:0;transform:translate3d(-210%,-180%,620px) rotateZ(-52deg) rotateX(35deg) scale(.7);filter:blur(4px) saturate(1.6)}',
    '.slide[data-tx="explode"].out-above .tx-group>*:nth-child(6n+2){opacity:0;transform:translate3d(220%,-220%,-480px) rotateZ(48deg) rotateY(-40deg) scale(.55);filter:blur(5px) hue-rotate(-35deg)}',
    '.slide[data-tx="explode"].out-above .tx-group>*:nth-child(6n+3){opacity:0;transform:translate3d(-240%,210%,780px) rotateZ(62deg) rotateY(55deg) scale(.9);filter:blur(3px) brightness(1.4)}',
    '.slide[data-tx="explode"].out-above .tx-group>*:nth-child(6n+4){opacity:0;transform:translate3d(260%,180%,-260px) rotateZ(-38deg) rotateX(-42deg) scale(.6);filter:blur(6px) saturate(.4)}',
    '.slide[data-tx="explode"].out-above .tx-group>*:nth-child(6n+5){opacity:0;transform:translate3d(-80%,-260%,500px) rotateZ(18deg) rotateY(80deg) scale(.4);filter:blur(4px) hue-rotate(45deg)}',
    '.slide[data-tx="explode"].out-above .tx-group>*:nth-child(6n+6){opacity:0;transform:translate3d(90%,240%,-420px) rotateZ(-72deg) rotateX(60deg) scale(.5);filter:blur(5px) brightness(.6)}',
    '.slide[data-tx="explode"].out-below .tx-group>*{opacity:0;transform:translate3d(0,8vh,-80px) scale(.9);filter:blur(2px)}',
    '.slide[data-tx="explode"].in-view .tx-group>*{opacity:1;filter:none;transform:none}',
    '.slide[data-tx="fold"] .slide-inner{transform:perspective(800px) rotateX(-38deg) translateY(50px);opacity:0;transition:transform .9s cubic-bezier(.16,1,.3,1),opacity .6s ease}',
    '.slide[data-tx="fold"].in-view .slide-inner{transform:perspective(800px) rotateX(0) translateY(0);opacity:1}',
    '.slide[data-tx="warp"] .slide-inner{transform:skewX(-10deg) translateX(-70px) scale(.97);opacity:0;transition:transform .75s cubic-bezier(.16,1,.3,1),opacity .5s ease}',
    '.slide[data-tx="warp"].in-view .slide-inner{transform:skewX(0) translateX(0) scale(1);opacity:1}',
    '@keyframes glitch-in{0%{clip-path:inset(45% 0 48% 0);transform:translate(-10px,0);opacity:0}12%{clip-path:inset(8% 0 82% 0);transform:translate(10px,0)}25%{clip-path:inset(72% 0 8% 0);transform:translate(-5px,0)}38%{clip-path:inset(28% 0 42% 0);transform:translate(5px,0);opacity:.5}55%{clip-path:inset(0 0 0 0);transform:translate(0,0);opacity:.8}100%{clip-path:inset(0 0 0 0);transform:translate(0,0);opacity:1}}',
    '.slide[data-tx="glitch"] .slide-inner{opacity:0}',
    '.slide[data-tx="glitch"].in-view .slide-inner{animation:glitch-in .65s ease forwards}',
    '.slide[data-tx="glitch"].out-above .slide-inner,.slide[data-tx="glitch"].out-below .slide-inner{opacity:0;animation:none}',
    '.slide[data-tx="dropzoom"] .slide-inner{transform:scale(1.18) translateY(-65px);opacity:0;transition:transform .9s cubic-bezier(.34,1.56,.64,1),opacity .5s ease}',
    '.slide[data-tx="dropzoom"].in-view .slide-inner{transform:scale(1) translateY(0);opacity:1}',
    '.slide[data-tx="prism"] .slide-inner{transform:perspective(1000px) rotateY(22deg) scale(.88);opacity:0;transition:transform 1s cubic-bezier(.16,1,.3,1),opacity .7s ease}',
    '.slide[data-tx="prism"].in-view .slide-inner{transform:perspective(1000px) rotateY(0) scale(1);opacity:1}',
    '.hero-tag{font-family:var(--fm);font-size:11px;letter-spacing:4px;text-transform:uppercase;color:var(--accent);margin-bottom:22px}',
    '.hero-title{font-family:var(--fb);font-weight:400;opacity:.58;margin-bottom:36px;max-width:600px}',
    '.hero-divider{width:44px;height:2px;background:var(--accent);margin-bottom:28px;opacity:0;transform:scaleX(0);transform-origin:left;transition:opacity .5s ease .4s,transform .5s ease .4s}',
    '.in-view .hero-divider{opacity:1;transform:scaleX(1)}',
    '.hero-signature{display:flex;align-items:center;gap:10px;font-size:14px;margin-bottom:7px}',
    '.h-name{font-weight:600}.h-dot{width:4px;height:4px;border-radius:50%;background:var(--accent)}.h-role{opacity:.48}',
    '.hero-company{font-family:var(--fm);font-size:11px;letter-spacing:2px;opacity:.35}',
    '.scroll-cue{position:absolute;bottom:36px;left:50%;transform:translateX(-50%);font-family:var(--fm);font-size:10px;letter-spacing:3px;text-transform:uppercase;opacity:.28;animation:pulse-cue 2.2s ease-in-out infinite}',
    '@keyframes pulse-cue{0%,100%{opacity:.28;transform:translateX(-50%) translateY(0)}50%{opacity:.55;transform:translateX(-50%) translateY(-4px)}}',
    '.demo-embed-wrap{width:100%;max-width:820px;aspect-ratio:16/9;border-radius:14px;overflow:hidden;border:1px solid var(--wire);margin-top:28px;opacity:0;transform:translateY(20px);transition:opacity .6s ease .3s,transform .6s ease .3s}',
    '.in-view .demo-embed-wrap{opacity:1;transform:translateY(0)}',
    '.demo-iframe{width:100%;height:100%;border:none}',
    '.demo-placeholder{width:100%;max-width:580px;margin-top:28px}',
    '.demo-ph-inner{background:var(--mist);border:1px dashed var(--wire);border-radius:14px;padding:56px 36px;text-align:center}',
    '.demo-ph-icon{font-size:44px;color:var(--accent);opacity:.38;margin-bottom:14px}',
    '.demo-ph-inner p{opacity:.5;font-size:14px;margin-bottom:20px}',
    '.demo-ph-link{display:inline-block;padding:11px 22px;background:var(--accent);color:var(--bg);text-decoration:none;border-radius:8px;font-weight:700;font-size:13px}',
    '#hud{position:fixed;inset:0;pointer-events:none;z-index:1000}',
    '#progress-bar{position:absolute;top:0;left:0;height:2px;background:var(--accent);transition:width .4s ease;width:0}',
    '#hud-top{position:absolute;top:24px;left:28px;right:28px;display:flex;align-items:center;justify-content:space-between}',
    '#hud-company,#hud-counter{font-family:var(--fm);font-size:10px;letter-spacing:3px;text-transform:uppercase;opacity:.28}',
    '#dot-nav{position:absolute;right:20px;top:50%;transform:translateY(-50%);display:flex;flex-direction:column;gap:7px;pointer-events:all}',
    '#dot-nav button{width:5px;height:5px;border-radius:50%;border:1px solid var(--fg);background:transparent;cursor:pointer;opacity:.18;transition:opacity .25s,background .25s,transform .25s;padding:0}',
    '#dot-nav button.active{background:var(--accent);border-color:var(--accent);opacity:1;transform:scale(1.5)}',
    '#dot-nav button:hover{opacity:.5}',
    '#hud-label{position:absolute;bottom:24px;left:28px;font-family:var(--fm);font-size:10px;letter-spacing:3px;text-transform:uppercase;opacity:.22}',
    // ─── Cinematic polish layer — closes the gap to the reference deck ───
    // Ambient noise overlay (canvas-grain texture, low opacity, overlay-blend)
    "body::before{content:'';position:fixed;inset:0;pointer-events:none;z-index:9999;opacity:.3;mix-blend-mode:overlay;background-image:url(\"data:image/svg+xml,%3Csvg viewBox='0 0 512 512' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='0.04'/%3E%3C/svg%3E\")}",
    // Custom cursor — ring + dot, mix-blend-mode:difference, hover expand on interactives
    '.cursor,.cursor-dot{position:fixed;top:0;left:0;pointer-events:none;z-index:9998;border-radius:50%;mix-blend-mode:difference;transition:transform .18s cubic-bezier(.2,.8,.2,1),width .25s,height .25s,background .2s;will-change:transform}',
    '.cursor{width:26px;height:26px;border:1px solid var(--accent);transform:translate(-50%,-50%)}',
    '.cursor-dot{width:4px;height:4px;background:var(--accent);transform:translate(-50%,-50%)}',
    '.cursor.hov{width:60px;height:60px;background:color-mix(in srgb,var(--accent) 12%,transparent);border-color:var(--accent)}',
    '@media (hover:none),(max-width:900px){.cursor,.cursor-dot{display:none}}',
    // Radial mask on the grid so it fades at edges (less "flat background")
    '.slide-grid{mask-image:radial-gradient(ellipse 70% 60% at 50% 40%,#000 0%,transparent 80%);-webkit-mask-image:radial-gradient(ellipse 70% 60% at 50% 40%,#000 0%,transparent 80%);opacity:.32}',
    // Display-type rhythm matching the reference (sub-title was too small)
    '.slide-sub{font-family:var(--fh);font-weight:800;font-size:clamp(22px,2.6vw,36px);line-height:1.1;letter-spacing:.5px;color:var(--accent);text-transform:uppercase;opacity:1;margin-bottom:22px;max-width:760px}',
    '.slide-tag{font-family:var(--fm);font-size:11px;font-weight:500;color:var(--accent);letter-spacing:3px;text-transform:uppercase;margin-bottom:24px;display:inline-flex;align-items:center;gap:12px}',
    // Marquee bands — full-viewport section break with animated text rows
    '.marquee-section{position:relative;min-height:100vh;background:var(--bg);overflow:hidden;border-top:1px solid var(--wire);border-bottom:1px solid var(--wire);display:flex;flex-direction:column;justify-content:center;gap:18px;scroll-snap-align:start;scroll-snap-stop:always;padding:40px 0}',
    '.marquee-row{display:flex;gap:80px;white-space:nowrap;animation:marq-l 48s linear infinite;will-change:transform}',
    '.marquee-row.reverse{animation-name:marq-r;animation-duration:52s}',
    '.marquee-row span{font-family:var(--fh);font-weight:900;font-style:italic;font-size:clamp(48px,8vw,120px);line-height:1;letter-spacing:-1.5px;color:var(--snow);text-transform:uppercase;display:inline-flex;align-items:center;gap:80px}',
    ".marquee-row span::after{content:'';display:inline-block;width:10px;height:10px;border-radius:50%;background:var(--accent);box-shadow:0 0 16px var(--accent);flex-shrink:0}",
    '.marquee-row.muted span{color:transparent;-webkit-text-stroke:1.2px var(--mist)}',
    '.marquee-row.muted span::after{background:transparent;border:1px solid var(--mist);box-shadow:none}',
    '@keyframes marq-l{from{transform:translate3d(0,0,0)}to{transform:translate3d(-50%,0,0)}}',
    '@keyframes marq-r{from{transform:translate3d(-50%,0,0)}to{transform:translate3d(0,0,0)}}',
    // Bespoke slide layouts (problem grid / fix checks / how flow / competition matrix)
    '.prob-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:28px;margin-top:32px}',
    '.prob-card{background:var(--surface);border:1px solid var(--wire);border-radius:14px;padding:28px 26px;position:relative;overflow:hidden;transition:border-color .25s}',
    '.prob-card:hover{border-color:var(--accent)}',
    ".prob-card::before{content:'';position:absolute;top:0;left:0;width:40px;height:2px;background:var(--accent)}",
    '.prob-num{font-family:var(--fm);font-size:10px;color:var(--accent);letter-spacing:2px;margin-bottom:16px}',
    '.prob-head{font-family:var(--fh);font-weight:800;font-size:22px;line-height:1.15;margin-bottom:14px;text-transform:uppercase;letter-spacing:.5px}',
    '.prob-body{font-size:13px;opacity:.65;line-height:1.6;margin-bottom:14px}',
    '.prob-foot{font-family:var(--fm);font-size:11px;color:var(--accent);line-height:1.5;padding-top:14px;border-top:1px dashed var(--wire)}',
    '@media(max-width:900px){.prob-grid{grid-template-columns:1fr;gap:16px}}',
    '.fix-checks{display:grid;grid-template-columns:repeat(5,1fr);gap:14px;margin:24px 0 28px}',
    '.fix-check{background:var(--surface);border:1px solid var(--wire);border-radius:10px;padding:14px;display:flex;flex-direction:column;gap:8px;font-size:12px;line-height:1.4}',
    '.fix-check::before{content:"✓";display:inline-block;width:18px;height:18px;border-radius:50%;background:var(--accent);color:var(--bg);text-align:center;font-weight:900;font-size:11px;line-height:18px}',
    '@media(max-width:900px){.fix-checks{grid-template-columns:repeat(2,1fr)}}',
    '.how-flow{display:grid;grid-template-columns:repeat(4,1fr);gap:18px;margin-top:24px;position:relative}',
    '.how-step{background:var(--surface);border:1px solid var(--wire);border-radius:14px;padding:24px 20px;position:relative}',
    '.how-step .how-num{font-family:var(--fh);font-weight:900;font-size:48px;color:var(--accent);line-height:1;margin-bottom:8px;opacity:.85}',
    '.how-step .how-head{font-family:var(--fh);font-weight:800;font-size:16px;text-transform:uppercase;letter-spacing:.5px;margin-bottom:8px}',
    '.how-step .how-body{font-size:12px;opacity:.62;line-height:1.55}',
    '@media(max-width:900px){.how-flow{grid-template-columns:1fr 1fr;gap:12px}}',
    '.comp-matrix{display:grid;grid-template-columns:1.4fr repeat(3,1fr);gap:0;margin-top:24px;border:1px solid var(--wire);border-radius:14px;overflow:hidden;font-size:13px}',
    '.comp-matrix>div{padding:14px 16px;border-bottom:1px solid var(--wire);border-right:1px solid var(--wire)}',
    '.comp-matrix>div:nth-child(4n){border-right:none}',
    '.comp-head{background:var(--surface);font-family:var(--fm);font-size:11px;text-transform:uppercase;letter-spacing:2px;color:var(--accent)}',
    '.comp-row-label{font-weight:700}',
    '.comp-y{color:var(--accent);font-weight:900;font-size:18px;text-align:center}',
    '.comp-n{opacity:.35;font-weight:900;font-size:18px;text-align:center}',
    '@media(max-width:900px){.comp-matrix{font-size:11px}}',
    // ─── VALIDATION VARIANTS ─────────────────────────────────────────
    '.val-hero{display:grid;grid-template-columns:1.4fr 1fr;gap:36px;align-items:center;margin-top:36px}',
    '.val-hero-num{font-family:var(--fh);font-weight:900;font-size:clamp(120px,18vw,260px);line-height:.85;letter-spacing:-.04em;color:var(--accent);font-style:italic;grid-row:1/3}',
    '.val-hero-lbl{font-family:var(--fm);font-size:13px;letter-spacing:3px;text-transform:uppercase;opacity:.55;align-self:start;padding-top:24px}',
    '.val-hero-side{display:flex;flex-direction:column;gap:16px}',
    '.val-side-stat{padding:18px 20px;background:var(--surface);border:1px solid var(--wire);border-radius:14px;border-left:3px solid var(--accent)}',
    '.val-side-num{font-family:var(--fh);font-weight:900;font-size:32px;color:var(--accent);line-height:1}',
    '.val-side-lbl{font-family:var(--fm);font-size:10px;letter-spacing:2px;text-transform:uppercase;opacity:.55;margin-top:6px}',
    '@media(max-width:900px){.val-hero{grid-template-columns:1fr}.val-hero-num{font-size:clamp(80px,20vw,140px)}}',
    '.val-cohort{margin-top:32px}',
    '.val-curve{width:100%;height:200px;background:var(--surface);border:1px solid var(--wire);border-radius:14px;padding:24px}',
    '.val-curve-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-top:18px}',
    '.val-curve-stat{padding:18px 20px;background:var(--surface);border:1px solid var(--wire);border-radius:14px}',
    '.val-curve-num{font-family:var(--fh);font-weight:900;font-size:36px;color:var(--accent);line-height:1}',
    '.val-curve-lbl{font-family:var(--fm);font-size:10px;letter-spacing:2px;text-transform:uppercase;opacity:.55;margin-top:6px}',
    '@media(max-width:900px){.val-curve-stats{grid-template-columns:repeat(2,1fr)}}',
    '.val-wall{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-top:32px}',
    '.val-logo-tile{aspect-ratio:1;background:var(--surface);border:1px solid var(--wire);border-radius:14px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:8px;padding:16px;transition:border-color .25s}',
    '.val-logo-tile:hover{border-color:var(--accent)}',
    '.val-logo-tile img{max-width:60%;max-height:50%;object-fit:contain;filter:grayscale(1) opacity(.8)}',
    '.val-logo-init{font-family:var(--fh);font-weight:900;font-size:28px;color:var(--accent)}',
    '.val-logo-name{font-family:var(--fm);font-size:10px;letter-spacing:1px;opacity:.55;text-align:center;line-height:1.2}',
    '@media(max-width:900px){.val-wall{grid-template-columns:repeat(3,1fr)}}',
    '.val-quotes{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:18px;margin-top:32px}',
    '.val-quote{background:var(--surface);border:1px solid var(--wire);border-left:3px solid var(--accent);border-radius:14px;padding:24px 26px;position:relative}',
    '.val-quote-mark{font-family:var(--fh);font-weight:900;font-size:64px;line-height:.5;color:var(--accent);opacity:.5;margin-bottom:6px}',
    '.val-quote-text{font-size:15px;line-height:1.55;margin-bottom:14px;opacity:.85}',
    '.val-quote-author{font-family:var(--fm);font-size:11px;letter-spacing:1px;opacity:.6}',
    // ─── COMPETITION VARIANTS ────────────────────────────────────────
    '.comp-quad{margin-top:32px;display:flex;justify-content:center}',
    '.comp-quad-axes{position:relative;width:min(620px,90%);aspect-ratio:1;background:var(--surface);border:1px solid var(--wire);border-radius:14px}',
    ".comp-quad-axes::before,.comp-quad-axes::after{content:'';position:absolute;background:var(--wire)}",
    '.comp-quad-axes::before{left:50%;top:0;bottom:0;width:1px}',
    '.comp-quad-axes::after{top:50%;left:0;right:0;height:1px}',
    '.comp-quad-x-label{position:absolute;bottom:-26px;left:50%;transform:translateX(-50%);font-family:var(--fm);font-size:11px;letter-spacing:2px;text-transform:uppercase;opacity:.55}',
    '.comp-quad-y-label{position:absolute;top:50%;left:-12px;transform:translate(-100%,-50%) rotate(-90deg);transform-origin:right center;font-family:var(--fm);font-size:11px;letter-spacing:2px;text-transform:uppercase;opacity:.55;white-space:nowrap}',
    '.comp-quad-dot{position:absolute;width:18px;height:18px;border-radius:50%;background:var(--mist);border:2px solid var(--bg);transform:translate(-50%,-50%);transition:transform .3s var(--ease-enter,cubic-bezier(.16,1,.3,1))}',
    '.comp-quad-dot.is-us{width:26px;height:26px;background:var(--accent);box-shadow:0 0 0 4px color-mix(in srgb,var(--accent) 24%,transparent),0 0 18px var(--accent)}',
    '.comp-quad-dot-label{position:absolute;top:calc(100% + 6px);left:50%;transform:translateX(-50%);white-space:nowrap;font-family:var(--fm);font-size:10px;letter-spacing:1px;opacity:.7}',
    '.comp-radar{margin-top:32px;display:grid;grid-template-columns:1fr auto;gap:32px;align-items:center}',
    '.comp-radar-svg{width:min(420px,80vw);height:auto}',
    '.comp-radar-legend{display:flex;flex-direction:column;gap:14px}',
    ".comp-radar-key{display:inline-flex;align-items:center;gap:10px;font-family:var(--fm);font-size:11px;letter-spacing:1.5px;text-transform:uppercase;opacity:.75}",
    ".comp-radar-key span{display:inline-block;width:14px;height:14px;border-radius:3px;background:var(--c)}",
    '@media(max-width:900px){.comp-radar{grid-template-columns:1fr}}',
    '.comp-anti{display:flex;flex-direction:column;gap:16px;margin-top:32px;max-width:880px}',
    '.comp-anti-row{display:grid;grid-template-columns:1fr 1fr;gap:1px;background:var(--wire);border-radius:18px;overflow:hidden}',
    '.comp-anti-are,.comp-anti-not{background:var(--surface);padding:24px 28px;display:flex;flex-direction:column;gap:10px}',
    '.comp-anti-not{background:var(--bg);color:var(--mist)}',
    '.comp-anti-lbl{font-family:var(--fm);font-size:10px;letter-spacing:3px;text-transform:uppercase;opacity:.5}',
    '.comp-anti-val{font-family:var(--fh);font-weight:800;font-size:22px;text-transform:uppercase;letter-spacing:.5px;color:var(--accent)}',
    '.comp-anti-val.muted{color:var(--mist);text-decoration:line-through;text-decoration-color:rgba(255,255,255,.2)}',
    '@media(max-width:900px){.comp-anti-row{grid-template-columns:1fr}}',
    // ─── CUSTOMERS VARIANTS ──────────────────────────────────────────
    '.cust-arch{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin-top:32px}',
    '.cust-arch-card{background:var(--surface);border:1px solid var(--wire);border-radius:18px;padding:28px 26px;position:relative;overflow:hidden}',
    '.cust-arch-card::before{content:"";position:absolute;top:0;left:0;width:40px;height:3px;background:var(--accent)}',
    '.cust-arch-num{font-family:var(--fh);font-weight:900;font-size:42px;color:var(--accent);line-height:1;font-style:italic;margin-bottom:14px;opacity:.85}',
    '.cust-arch-name{font-family:var(--fh);font-weight:800;font-size:18px;text-transform:uppercase;letter-spacing:.5px;margin-bottom:10px}',
    '.cust-arch-desc{font-size:13px;line-height:1.55;opacity:.65}',
    '@media(max-width:900px){.cust-arch{grid-template-columns:1fr}}',
    '.cust-quotes{display:flex;flex-direction:column;gap:14px;margin-top:32px;max-width:880px}',
    '.cust-quote-card{display:grid;grid-template-columns:64px 1fr;gap:20px;background:var(--surface);border:1px solid var(--wire);border-radius:14px;padding:20px 24px;align-items:start}',
    '.cust-quote-avatar{width:48px;height:48px;border-radius:50%;background:var(--accent);color:var(--bg);font-family:var(--fh);font-weight:900;font-size:20px;display:flex;align-items:center;justify-content:center}',
    '.cust-quote-text{font-size:15px;line-height:1.55;margin-bottom:10px;font-style:italic;opacity:.9}',
    '.cust-quote-name{font-family:var(--fm);font-size:11px;letter-spacing:1px;opacity:.6}',
    '.cust-quote-role{opacity:.5}',
    '.cust-timeline{display:flex;flex-direction:column;gap:14px;margin-top:32px;position:relative;padding-left:28px;max-width:780px}',
    ".cust-timeline::before{content:'';position:absolute;top:8px;bottom:8px;left:7px;width:2px;background:linear-gradient(var(--accent),var(--wire))}",
    '.cust-timeline-step{position:relative;background:var(--surface);border:1px solid var(--wire);border-radius:14px;padding:18px 22px}',
    ".cust-timeline-marker{position:absolute;left:-28px;top:22px;width:16px;height:16px;border-radius:50%;background:var(--accent);box-shadow:0 0 0 4px var(--bg)}",
    '.cust-timeline-when{font-family:var(--fm);font-size:10px;letter-spacing:2px;text-transform:uppercase;color:var(--accent);margin-bottom:6px}',
    '.cust-timeline-what{font-family:var(--fh);font-weight:800;font-size:16px;text-transform:uppercase;letter-spacing:.5px}',
    '.cust-timeline-detail{font-size:13px;line-height:1.5;opacity:.65;margin-top:6px}',
    '.cust-icons{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-top:32px}',
    '.cust-icon-tile{background:var(--surface);border:1px solid var(--wire);border-radius:14px;padding:18px;display:flex;flex-direction:column;align-items:center;gap:10px;text-align:center}',
    '.cust-icon-glyph{width:42px;height:42px;border-radius:10px;background:color-mix(in srgb,var(--accent) 14%,transparent);color:var(--accent);font-family:var(--fh);font-weight:900;font-size:18px;display:flex;align-items:center;justify-content:center}',
    '.cust-icon-name{font-family:var(--fm);font-size:10px;letter-spacing:1px;line-height:1.3}',
    '@media(max-width:900px){.cust-icons{grid-template-columns:repeat(3,1fr)}}',
    // ─── TEAM & ASK VARIANTS ─────────────────────────────────────────
    '.ask-split{display:grid;grid-template-columns:1.15fr 1fr;gap:24px;margin-top:32px}',
    '.ask-panel-funds{background:var(--surface);border:1px solid var(--wire);border-radius:18px;padding:28px}',
    '.ask-panel-title{font-family:var(--fh);font-weight:800;font-size:14px;text-transform:uppercase;letter-spacing:1px;color:var(--accent);margin-bottom:16px}',
    '.ask-panel-list{list-style:none;display:flex;flex-direction:column;gap:12px}',
    '.ask-panel-list li{font-size:13px;line-height:1.55;padding-left:22px;position:relative}',
    ".ask-panel-list li::before{content:'';position:absolute;left:0;top:.7em;width:12px;height:2px;background:var(--accent)}",
    '.ask-panel-cta{background:var(--accent);color:var(--bg);border-radius:18px;padding:32px;display:flex;flex-direction:column;justify-content:center;text-align:left}',
    '.ask-cta-num{font-family:var(--fh);font-weight:900;font-size:clamp(48px,7vw,96px);line-height:.9;letter-spacing:-.02em;font-style:italic}',
    '.ask-cta-lbl{font-family:var(--fm);font-size:11px;letter-spacing:3px;text-transform:uppercase;margin-top:8px;opacity:.7}',
    '.ask-cta-milestone{font-size:14px;margin-top:24px;line-height:1.5;opacity:.85}',
    '@media(max-width:900px){.ask-split{grid-template-columns:1fr}}',
    '.team-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin-top:32px}',
    '.team-card{background:var(--surface);border:1px solid var(--wire);border-radius:18px;padding:24px;text-align:center}',
    '.team-photo{width:80px;height:80px;border-radius:50%;object-fit:cover;margin:0 auto 14px;background:var(--bg);border:2px solid var(--accent)}',
    '.team-photo-mono{display:flex;align-items:center;justify-content:center;font-family:var(--fh);font-weight:900;font-size:28px;color:var(--accent)}',
    '.team-name{font-family:var(--fh);font-weight:800;font-size:18px;text-transform:uppercase;letter-spacing:.5px;margin-bottom:4px}',
    '.team-role{font-family:var(--fm);font-size:10px;letter-spacing:2px;text-transform:uppercase;color:var(--accent);margin-bottom:10px}',
    '.team-cred{font-size:12px;line-height:1.4;opacity:.65}',
    '@media(max-width:900px){.team-grid{grid-template-columns:1fr 1fr}}',
    '.cap-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:14px;margin-top:32px;max-width:780px}',
    '.cap-tile{background:var(--surface);border:1px solid var(--wire);border-radius:18px;padding:26px}',
    '.cap-lbl{font-family:var(--fm);font-size:10px;letter-spacing:3px;text-transform:uppercase;opacity:.55;margin-bottom:10px}',
    '.cap-val{font-family:var(--fh);font-weight:900;font-size:clamp(36px,5vw,56px);line-height:1;color:var(--accent);font-style:italic;letter-spacing:-.02em}',
    '.cap-val-sm{font-size:clamp(22px,3vw,32px);font-style:normal}',
    '.cap-progress{grid-column:1/-1}',
    '.cap-bar{height:10px;background:var(--bg);border:1px solid var(--wire);border-radius:6px;overflow:hidden;margin-top:14px}',
    '.cap-bar-fill{height:100%;background:var(--accent);transition:width 1s var(--ease-enter,cubic-bezier(.16,1,.3,1))}',
    '.ms-road{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:24px;margin-top:48px;position:relative;padding-top:24px}',
    ".ms-road-line{position:absolute;top:30px;left:5%;right:5%;height:2px;background:linear-gradient(90deg,var(--accent),var(--wire))}",
    '.ms-stop{display:flex;flex-direction:column;align-items:flex-start}',
    '.ms-dot{width:14px;height:14px;border-radius:50%;background:var(--wire);border:3px solid var(--bg);margin-top:-7px;margin-bottom:14px}',
    '.ms-dot-current{background:var(--accent);box-shadow:0 0 0 4px color-mix(in srgb,var(--accent) 24%,transparent),0 0 14px var(--accent)}',
    '.ms-when{font-family:var(--fm);font-size:10px;letter-spacing:2px;text-transform:uppercase;color:var(--accent);margin-bottom:6px}',
    '.ms-what{font-family:var(--fh);font-weight:800;font-size:15px;text-transform:uppercase;letter-spacing:.5px;margin-bottom:6px;line-height:1.2}',
    '.ms-detail{font-size:12px;line-height:1.5;opacity:.6}',
    // ─── PROBLEM VARIANTS (stat-overlay / quote-evidence / before-state) ─
    '.prob-stat{display:grid;grid-template-columns:1.4fr 1fr;gap:32px;align-items:center;margin-top:36px}',
    '.prob-stat-hero{padding:32px;background:var(--surface);border:1px solid var(--wire);border-left:4px solid var(--accent);border-radius:18px}',
    '.prob-stat-num{font-family:var(--fh);font-weight:900;font-size:clamp(80px,12vw,160px);line-height:.88;letter-spacing:-.04em;color:var(--accent);font-style:italic}',
    '.prob-stat-lbl{font-family:var(--fm);font-size:13px;letter-spacing:3px;text-transform:uppercase;opacity:.65;margin-top:8px}',
    '.prob-stat-sub{font-size:14px;line-height:1.5;opacity:.6;margin-top:14px;max-width:480px}',
    '.prob-stat-side{display:flex;flex-direction:column;gap:12px}',
    '.prob-stat-fact{padding:14px 18px;background:var(--surface);border:1px solid var(--wire);border-radius:12px;font-size:13px;line-height:1.5}',
    '@media(max-width:900px){.prob-stat{grid-template-columns:1fr}}',
    '.prob-quotes{display:flex;flex-direction:column;gap:14px;margin-top:32px;max-width:860px}',
    '.prob-quote-card{background:var(--surface);border:1px solid var(--wire);border-left:3px solid var(--accent);border-radius:14px;padding:22px 26px}',
    '.prob-quote-mark{font-family:var(--fh);font-weight:900;font-size:54px;line-height:.5;color:var(--accent);opacity:.55;margin-bottom:4px}',
    '.prob-quote-text{font-size:16px;line-height:1.5;margin-bottom:12px;font-style:italic;opacity:.88}',
    '.prob-quote-author{font-family:var(--fm);font-size:11px;letter-spacing:1.5px;opacity:.55}',
    '.prob-before{display:grid;grid-template-columns:1fr auto 1fr;gap:18px;align-items:stretch;margin-top:32px}',
    '.prob-before-col{background:var(--surface);border:1px solid var(--wire);border-radius:18px;padding:24px 26px}',
    '.prob-before-sq{border-left:3px solid var(--mist)}',
    '.prob-before-wish{border-left:3px solid var(--accent)}',
    '.prob-before-lbl{font-family:var(--fm);font-size:11px;letter-spacing:3px;text-transform:uppercase;color:var(--accent);margin-bottom:14px}',
    '.prob-before-sq .prob-before-lbl{color:var(--mist)}',
    '.prob-before-col ul{list-style:none;display:flex;flex-direction:column;gap:10px}',
    '.prob-before-col li{font-size:13px;line-height:1.5;padding-left:20px;position:relative;opacity:.85}',
    ".prob-before-col li::before{content:'';position:absolute;left:0;top:.65em;width:10px;height:2px;background:var(--accent)}",
    ".prob-before-sq li::before{background:var(--mist);opacity:.5}",
    '.prob-before-arrow{font-family:var(--fh);font-weight:900;font-size:42px;color:var(--accent);display:flex;align-items:center;opacity:.75}',
    '@media(max-width:900px){.prob-before{grid-template-columns:1fr}.prob-before-arrow{transform:rotate(90deg)}}',
    // ─── FIX VARIANTS (before-after / three-pillar / one-big-thing) ────
    '.fix-ba{display:grid;grid-template-columns:1fr auto 1fr;gap:18px;align-items:stretch;margin-top:32px}',
    '.fix-ba-col{background:var(--surface);border:1px solid var(--wire);border-radius:18px;padding:26px 28px}',
    '.fix-ba-before{opacity:.7}',
    '.fix-ba-after{border-left:3px solid var(--accent)}',
    '.fix-ba-lbl{font-family:var(--fm);font-size:11px;letter-spacing:3px;text-transform:uppercase;margin-bottom:14px}',
    '.fix-ba-before .fix-ba-lbl{color:var(--mist)}',
    '.fix-ba-after .fix-ba-lbl{color:var(--accent)}',
    '.fix-ba-col ul{list-style:none;display:flex;flex-direction:column;gap:10px}',
    '.fix-ba-col li{font-size:13px;line-height:1.5;padding-left:22px;position:relative}',
    ".fix-ba-before li::before{content:'×';position:absolute;left:0;color:var(--mist);opacity:.6;font-weight:700}",
    ".fix-ba-after li::before{content:'✓';position:absolute;left:0;color:var(--accent);font-weight:700}",
    '.fix-ba-arrow{font-family:var(--fh);font-weight:900;font-size:42px;color:var(--accent);display:flex;align-items:center}',
    '@media(max-width:900px){.fix-ba{grid-template-columns:1fr}.fix-ba-arrow{transform:rotate(90deg)}}',
    '.fix-pillars{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin-top:32px}',
    '.fix-pillar{background:var(--surface);border:1px solid var(--wire);border-radius:18px;padding:32px 28px;text-align:center}',
    '.fix-pillar-icon{width:64px;height:64px;border-radius:16px;background:color-mix(in srgb,var(--accent) 16%,transparent);color:var(--accent);font-family:var(--fh);font-weight:900;font-size:28px;display:flex;align-items:center;justify-content:center;margin:0 auto 18px}',
    '.fix-pillar-name{font-family:var(--fh);font-weight:800;font-size:20px;text-transform:uppercase;letter-spacing:.5px;margin-bottom:12px}',
    '.fix-pillar-desc{font-size:13px;line-height:1.55;opacity:.65}',
    '@media(max-width:900px){.fix-pillars{grid-template-columns:1fr}}',
    '.fix-onething{margin-top:32px;max-width:880px}',
    '.fix-onething-statement{font-family:var(--fh);font-weight:900;font-size:clamp(36px,5vw,68px);line-height:1.1;letter-spacing:-.02em;color:var(--accent);text-transform:uppercase;margin-bottom:32px}',
    '.fix-onething-sup{display:flex;flex-direction:column;gap:14px;max-width:680px}',
    '.fix-onething-line{font-size:18px;line-height:1.5;padding-left:24px;position:relative;opacity:.75}',
    ".fix-onething-line::before{content:'';position:absolute;left:0;top:.7em;width:14px;height:2px;background:var(--accent)}",
    // ─── SITUATION VARIANTS (why-now-triple / shift-timeline / convergence / before-after-world) ─
    '.sit-triple{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin-top:32px}',
    '.sit-triple-card{background:var(--surface);border:1px solid var(--wire);border-radius:18px;padding:28px;position:relative;overflow:hidden}',
    ".sit-triple-card::before{content:'';position:absolute;top:0;right:0;width:80px;height:80px;background:radial-gradient(circle at top right,color-mix(in srgb,var(--accent) 18%,transparent),transparent 70%)}",
    '.sit-triple-num{font-family:var(--fh);font-weight:900;font-size:48px;color:var(--accent);line-height:1;margin-bottom:18px;font-style:italic;opacity:.9}',
    '.sit-triple-name{font-family:var(--fh);font-weight:800;font-size:20px;text-transform:uppercase;letter-spacing:.5px;margin-bottom:10px}',
    '.sit-triple-desc{font-size:13px;line-height:1.55;opacity:.65}',
    '@media(max-width:900px){.sit-triple{grid-template-columns:1fr}}',
    '.sit-timeline{display:flex;justify-content:space-between;gap:18px;margin-top:48px;position:relative;padding:24px 0}',
    ".sit-timeline-line{position:absolute;top:30px;left:0;right:0;height:2px;background:linear-gradient(90deg,var(--wire),var(--accent),var(--wire))}",
    '.sit-timeline-stop{flex:1;display:flex;flex-direction:column;align-items:flex-start;min-width:0}',
    '.sit-timeline-dot{width:14px;height:14px;border-radius:50%;background:var(--wire);border:3px solid var(--bg);margin-top:-7px;margin-bottom:14px}',
    '.sit-timeline-dot-now{background:var(--accent);box-shadow:0 0 0 4px color-mix(in srgb,var(--accent) 24%,transparent),0 0 14px var(--accent)}',
    '.sit-timeline-when{font-family:var(--fm);font-size:10px;letter-spacing:2px;text-transform:uppercase;color:var(--accent);margin-bottom:6px}',
    '.sit-timeline-what{font-family:var(--fh);font-weight:800;font-size:14px;text-transform:uppercase;letter-spacing:.4px;line-height:1.2}',
    '.sit-conv{display:grid;grid-template-columns:1fr 1fr;gap:32px;margin-top:32px;align-items:center}',
    '.sit-conv-lines{position:relative;aspect-ratio:1;background:var(--surface);border:1px solid var(--wire);border-radius:18px}',
    '.sit-conv-line{position:absolute;left:50%;top:50%;width:46%;height:2px;background:linear-gradient(90deg,var(--mist),var(--accent));transform-origin:left center;transform:rotate(calc((var(--i,0) - (var(--total,1) - 1) / 2) * 60deg))}',
    '.sit-conv-point{position:absolute;left:50%;top:50%;width:18px;height:18px;background:var(--accent);border-radius:50%;transform:translate(-50%,-50%);box-shadow:0 0 0 4px color-mix(in srgb,var(--accent) 24%,transparent),0 0 18px var(--accent)}',
    '.sit-conv-labels{display:flex;flex-direction:column;gap:14px}',
    '.sit-conv-trend{padding:16px 20px;background:var(--surface);border:1px solid var(--wire);border-left:3px solid var(--accent);border-radius:12px}',
    '.sit-conv-name{font-family:var(--fh);font-weight:800;font-size:16px;text-transform:uppercase;letter-spacing:.5px;margin-bottom:6px}',
    '.sit-conv-desc{font-size:12px;line-height:1.5;opacity:.65}',
    '@media(max-width:900px){.sit-conv{grid-template-columns:1fr}}',
    '.sit-world{display:grid;grid-template-columns:1fr auto 1fr;gap:18px;align-items:stretch;margin-top:32px}',
    '.sit-world-col{background:var(--surface);border:1px solid var(--wire);border-radius:18px;padding:26px 28px}',
    '.sit-world-old{opacity:.7}',
    '.sit-world-new{border-left:3px solid var(--accent)}',
    '.sit-world-lbl{font-family:var(--fm);font-size:11px;letter-spacing:3px;text-transform:uppercase;margin-bottom:14px}',
    '.sit-world-old .sit-world-lbl{color:var(--mist)}',
    '.sit-world-new .sit-world-lbl{color:var(--accent)}',
    '.sit-world-col ul{list-style:none;display:flex;flex-direction:column;gap:10px}',
    '.sit-world-col li{font-size:13px;line-height:1.5;padding-left:18px;position:relative}',
    ".sit-world-col li::before{content:'';position:absolute;left:0;top:.65em;width:8px;height:2px;background:var(--accent)}",
    ".sit-world-old li::before{background:var(--mist);opacity:.4}",
    '.sit-world-divider{display:flex;align-items:center;justify-content:center;font-family:var(--fh);font-weight:900;color:var(--accent);font-size:14px;letter-spacing:2px;text-transform:uppercase;writing-mode:vertical-rl;transform:rotate(180deg)}',
    '.sit-world-divider span{background:var(--accent);color:var(--bg);padding:8px 14px;border-radius:8px;writing-mode:horizontal-tb;transform:rotate(180deg);letter-spacing:1px}',
    '@media(max-width:900px){.sit-world{grid-template-columns:1fr}.sit-world-divider{writing-mode:horizontal-tb;transform:none}}',
    // ─── MARKET VARIANTS (tam-sam-som / waterfall-bars / verticals / growth-curve) ─
    '.mkt-rings{display:grid;grid-template-columns:1fr 1fr;gap:48px;align-items:center;margin-top:32px}',
    '.mkt-rings-svg{position:relative;aspect-ratio:1;width:100%;max-width:420px;justify-self:center}',
    '.mkt-ring{position:absolute;border-radius:50%;display:flex;align-items:flex-start;justify-content:center;padding-top:6%;font-family:var(--fh);font-weight:900;font-size:clamp(18px,2.4vw,28px);color:var(--accent);font-style:italic;letter-spacing:-.02em}',
    '.mkt-ring-1{inset:0;background:color-mix(in srgb,var(--accent) 8%,transparent);border:2px solid color-mix(in srgb,var(--accent) 40%,transparent)}',
    '.mkt-ring-2{inset:14%;background:color-mix(in srgb,var(--accent) 16%,transparent);border:2px solid color-mix(in srgb,var(--accent) 55%,transparent)}',
    '.mkt-ring-3{inset:32%;background:color-mix(in srgb,var(--accent) 36%,transparent);border:2px solid var(--accent);font-size:clamp(22px,3vw,40px);align-items:center;padding-top:0}',
    '.mkt-rings-legend{display:flex;flex-direction:column;gap:16px}',
    '.mkt-rings-row{display:flex;align-items:center;gap:14px;padding:16px 20px;background:var(--surface);border:1px solid var(--wire);border-radius:12px}',
    '.mkt-rings-dot{width:14px;height:14px;border-radius:50%;flex-shrink:0}',
    '.mkt-rings-dot-1{background:color-mix(in srgb,var(--accent) 50%,transparent)}',
    '.mkt-rings-dot-2{background:color-mix(in srgb,var(--accent) 75%,transparent)}',
    '.mkt-rings-dot-3{background:var(--accent)}',
    '.mkt-rings-lbl{font-family:var(--fm);font-size:11px;letter-spacing:2px;text-transform:uppercase;opacity:.55}',
    '.mkt-rings-val{font-family:var(--fh);font-weight:800;font-size:18px;color:var(--accent)}',
    '@media(max-width:900px){.mkt-rings{grid-template-columns:1fr}}',
    '.mkt-water{display:flex;flex-direction:column;gap:14px;margin-top:32px;max-width:780px}',
    '.mkt-water-row{display:grid;grid-template-columns:120px 1fr;gap:18px;align-items:center}',
    '.mkt-water-lbl{font-family:var(--fm);font-size:11px;letter-spacing:2px;text-transform:uppercase;opacity:.55}',
    '.mkt-water-bar{position:relative;height:48px;background:var(--surface);border:1px solid var(--wire);border-radius:10px;overflow:hidden}',
    '.mkt-water-bar-fill{position:absolute;left:0;top:0;bottom:0;width:var(--w,50%);background:linear-gradient(90deg,var(--accent),color-mix(in srgb,var(--accent) 50%,transparent));transition:width 1s var(--ease-enter,cubic-bezier(.16,1,.3,1))}',
    '.mkt-water-bar-val{position:relative;z-index:1;font-family:var(--fh);font-weight:900;font-size:22px;color:var(--bg);padding:0 16px;line-height:48px}',
    '.mkt-verticals{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-top:32px}',
    '.mkt-vertical-card{background:var(--surface);border:1px solid var(--wire);border-radius:14px;padding:22px 24px}',
    '.mkt-vertical-name{font-family:var(--fh);font-weight:800;font-size:16px;text-transform:uppercase;letter-spacing:.5px;margin-bottom:8px}',
    '.mkt-vertical-size{font-family:var(--fh);font-weight:900;font-size:28px;color:var(--accent);line-height:1;font-style:italic;margin-bottom:8px}',
    '.mkt-vertical-detail{font-size:12px;line-height:1.5;opacity:.6}',
    '@media(max-width:900px){.mkt-verticals{grid-template-columns:1fr 1fr}}',
    '.mkt-growth{margin-top:32px}',
    '.mkt-growth-svg{width:100%;height:auto;background:var(--surface);border:1px solid var(--wire);border-radius:18px;padding:20px}',
    '.mkt-growth-legend{display:flex;flex-wrap:wrap;gap:14px;margin-top:18px}',
    '.mkt-growth-callout{font-family:var(--fm);font-size:11px;letter-spacing:1px;padding:8px 14px;background:var(--surface);border:1px solid var(--wire);border-radius:8px;opacity:.75}',
    // ─── HOW VARIANTS (arch-stack / sequence-arrows / inputs-outputs) ────
    '.how-arch{display:flex;flex-direction:column;gap:0;margin-top:32px;max-width:700px;border:1px solid var(--wire);border-radius:18px;overflow:hidden;background:var(--surface)}',
    '.how-arch-layer{padding:20px 26px;border-bottom:1px solid var(--wire);display:grid;grid-template-columns:80px 1fr;gap:18px;align-items:center;position:relative}',
    '.how-arch-layer:last-child{border-bottom:none}',
    '.how-arch-layer:first-child{border-left:4px solid var(--accent)}',
    '.how-arch-lbl{font-family:var(--fm);font-size:10px;letter-spacing:2px;text-transform:uppercase;color:var(--accent);opacity:.6}',
    '.how-arch-name{font-family:var(--fh);font-weight:800;font-size:18px;text-transform:uppercase;letter-spacing:.5px}',
    '.how-arch-body{grid-column:2;font-size:13px;opacity:.65;margin-top:4px;line-height:1.5}',
    '.how-seq{display:flex;flex-wrap:nowrap;align-items:center;gap:0;margin-top:32px;overflow-x:auto;padding-bottom:8px}',
    '.how-seq-step{flex:0 0 auto;min-width:200px;background:var(--surface);border:1px solid var(--wire);border-radius:14px;padding:20px 22px;position:relative;display:flex;flex-direction:column;gap:8px}',
    '.how-seq-name{font-family:var(--fh);font-weight:800;font-size:16px;text-transform:uppercase;letter-spacing:.5px;color:var(--accent)}',
    '.how-seq-body{font-size:12px;line-height:1.5;opacity:.65}',
    '.how-seq-arrow{position:absolute;right:-22px;top:50%;transform:translateY(-50%);font-family:var(--fh);font-weight:900;font-size:32px;color:var(--accent);z-index:2}',
    '.how-io{display:grid;grid-template-columns:1fr 1fr 1fr;gap:18px;margin-top:32px;align-items:stretch}',
    '.how-io-col{background:var(--surface);border:1px solid var(--wire);border-radius:14px;padding:22px}',
    '.how-io-lbl{font-family:var(--fm);font-size:10px;letter-spacing:2px;text-transform:uppercase;color:var(--accent);margin-bottom:14px}',
    '.how-io-col ul{list-style:none;display:flex;flex-direction:column;gap:8px}',
    '.how-io-col li{font-size:13px;line-height:1.5;padding-left:18px;position:relative}',
    ".how-io-col li::before{content:'';position:absolute;left:0;top:.65em;width:10px;height:2px;background:var(--accent)}",
    '.how-io-engine{background:var(--accent);color:var(--bg);border-radius:14px;padding:22px;display:flex;flex-direction:column;align-items:center;text-align:center;justify-content:center}',
    '.how-io-engine-glyph{font-family:var(--fh);font-weight:900;font-size:48px;line-height:1;margin-bottom:8px;animation:io-spin 6s linear infinite}',
    '@keyframes io-spin{from{transform:rotate(0)}to{transform:rotate(360deg)}}',
    '.how-io-engine-name{font-family:var(--fh);font-weight:900;font-size:18px;text-transform:uppercase;letter-spacing:1px}',
    '.how-io-engine-body{font-size:12px;line-height:1.5;margin-top:8px;opacity:.85}',
    '@media(max-width:900px){.how-io{grid-template-columns:1fr}}',
    // ─── IMPLICATION VARIANTS (cost-counter / risk-fan / loss-frame / status-quo-failure) ─
    '.imp-cost{display:grid;grid-template-columns:1.4fr 1fr;gap:32px;align-items:center;margin-top:36px}',
    '.imp-cost-hero{padding:32px;background:var(--surface);border:1px solid var(--wire);border-left:4px solid var(--accent);border-radius:18px}',
    '.imp-cost-frame{font-family:var(--fm);font-size:12px;letter-spacing:2px;text-transform:uppercase;opacity:.55;margin-bottom:18px}',
    '.imp-cost-num{font-family:var(--fh);font-weight:900;font-size:clamp(80px,12vw,180px);line-height:.85;letter-spacing:-.04em;color:var(--accent);font-style:italic}',
    '.imp-cost-unit{font-family:var(--fm);font-size:13px;letter-spacing:3px;text-transform:uppercase;opacity:.7;margin-top:14px}',
    '.imp-cost-mults{display:flex;flex-direction:column;gap:14px}',
    '.imp-cost-mult{padding:18px 22px;background:var(--surface);border:1px solid var(--wire);border-radius:14px;display:flex;align-items:baseline;gap:14px}',
    '.imp-cost-mult-num{font-family:var(--fh);font-weight:900;font-size:28px;color:var(--accent);font-style:italic;line-height:1;flex-shrink:0}',
    '.imp-cost-mult-lbl{font-size:13px;line-height:1.5;opacity:.75}',
    '@media(max-width:900px){.imp-cost{grid-template-columns:1fr}}',
    '.imp-fan{display:flex;flex-direction:column;align-items:center;gap:0;margin-top:32px}',
    '.imp-fan-item{display:flex;align-items:center;gap:18px;padding:14px 20px;background:var(--surface);border:1px solid var(--wire);border-radius:12px;width:calc(100% - var(--i,0) * 60px);max-width:760px;position:relative;border-left:3px solid var(--accent)}',
    '.imp-fan-step{font-family:var(--fh);font-weight:900;font-size:18px;color:var(--accent);font-style:italic;flex-shrink:0}',
    '.imp-fan-text{font-size:14px;line-height:1.5;flex:1}',
    '.imp-fan-tail{font-family:var(--fh);font-weight:900;font-size:20px;color:var(--accent);margin:6px auto;opacity:.7}',
    '.imp-fan-end{font-family:var(--fm);font-size:11px;letter-spacing:3px;text-transform:uppercase;color:var(--accent);margin:14px 0;padding:8px 18px;border:1px dashed var(--accent);border-radius:8px}',
    '.imp-loss{display:flex;flex-direction:column;gap:0;margin-top:24px;max-width:760px}',
    '.imp-loss-intro{font-family:var(--fh);font-weight:800;font-size:24px;text-transform:uppercase;letter-spacing:.5px;color:var(--accent);margin-bottom:24px;font-style:italic}',
    '.imp-loss-step{display:grid;grid-template-columns:120px 1fr;gap:18px;align-items:start;padding:18px 0;border-bottom:1px solid var(--wire);position:relative}',
    '.imp-loss-step:last-child{border-bottom:none}',
    '.imp-loss-when{font-family:var(--fm);font-size:11px;letter-spacing:2px;text-transform:uppercase;color:var(--accent);padding-top:2px}',
    '.imp-loss-what{font-size:15px;line-height:1.55;opacity:.85}',
    '.imp-fail{margin-top:32px;border:1px solid var(--wire);border-radius:18px;overflow:hidden;background:var(--surface)}',
    '.imp-fail-row{display:grid;grid-template-columns:1fr 1fr;gap:0;padding:0;border-bottom:1px solid var(--wire)}',
    '.imp-fail-row:last-child{border-bottom:none}',
    '.imp-fail-row > div{padding:18px 24px}',
    '.imp-fail-row > div:first-child{border-right:1px solid var(--wire)}',
    '.imp-fail-head{background:var(--bg)}',
    '.imp-fail-head > div{font-family:var(--fm);font-size:11px;letter-spacing:2.5px;text-transform:uppercase;color:var(--accent)}',
    '.imp-fail-cost{font-family:var(--fh);font-weight:800;color:var(--accent)}',
    // ─── RISKS VARIANTS (mitigation-pairs / risk-radar / risk-narrative / risk-timeline) ─
    '.risk-pairs{display:flex;flex-direction:column;gap:14px;margin-top:32px}',
    '.risk-pair-row{display:grid;grid-template-columns:1fr auto 1fr;gap:14px;align-items:stretch}',
    '.risk-pair-risk,.risk-pair-mit{background:var(--surface);border:1px solid var(--wire);border-radius:14px;padding:18px 22px}',
    '.risk-pair-risk{border-left:3px solid var(--mist);opacity:.85}',
    '.risk-pair-mit{border-left:3px solid var(--accent)}',
    '.risk-pair-lbl{font-family:var(--fm);font-size:10px;letter-spacing:3px;text-transform:uppercase;color:var(--mist);margin-bottom:8px}',
    '.risk-pair-lbl-mit{color:var(--accent)}',
    '.risk-pair-text{font-size:14px;line-height:1.5}',
    '.risk-pair-arrow{display:flex;align-items:center;font-family:var(--fh);font-weight:900;font-size:24px;color:var(--accent)}',
    '@media(max-width:900px){.risk-pair-row{grid-template-columns:1fr}.risk-pair-arrow{transform:rotate(90deg);justify-content:center}}',
    '.risk-radar{margin-top:32px;display:grid;grid-template-columns:1fr;gap:18px}',
    '.risk-radar-grid{position:relative;aspect-ratio:1.4/1;max-width:680px;background:var(--surface);border:1px solid var(--wire);border-radius:18px}',
    '.risk-radar-axes{position:absolute;inset:32px}',
    ".risk-radar-axes::before,.risk-radar-axes::after{content:'';position:absolute;background:var(--wire)}",
    '.risk-radar-axes::before{left:50%;top:0;bottom:0;width:1px}',
    '.risk-radar-axes::after{top:50%;left:0;right:0;height:1px}',
    '.risk-radar-x-label{position:absolute;bottom:-28px;left:50%;transform:translateX(-50%);font-family:var(--fm);font-size:10px;letter-spacing:2px;text-transform:uppercase;opacity:.5}',
    '.risk-radar-y-label{position:absolute;top:50%;left:-12px;transform:translate(-100%,-50%) rotate(-90deg);transform-origin:right center;font-family:var(--fm);font-size:10px;letter-spacing:2px;text-transform:uppercase;opacity:.5;white-space:nowrap}',
    '.risk-radar-dot{position:absolute;width:14px;height:14px;border-radius:50%;background:var(--accent);transform:translate(-50%,-50%);box-shadow:0 0 0 4px color-mix(in srgb,var(--accent) 24%,transparent)}',
    '.risk-radar-dot-name{position:absolute;left:18px;top:50%;transform:translateY(-50%);white-space:nowrap;font-family:var(--fm);font-size:11px;letter-spacing:.5px;opacity:.85;padding:2px 8px;background:var(--surface);border-radius:6px}',
    '.risk-radar-mit{margin-top:14px;padding:14px 20px;background:var(--surface);border:1px solid var(--wire);border-left:3px solid var(--accent);border-radius:12px;font-size:13px;line-height:1.5;max-width:760px}',
    '.risk-timeline{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:18px;margin-top:48px;position:relative;padding-top:36px}',
    ".risk-timeline-line{position:absolute;top:40px;left:5%;right:5%;height:2px;background:linear-gradient(90deg,var(--accent),var(--wire),var(--accent))}",
    '.risk-timeline-stop{display:flex;flex-direction:column;align-items:flex-start;position:relative;padding-top:24px}',
    '.risk-timeline-bar{position:absolute;top:-12px;left:0;width:14px;height:14px;border-radius:50%;background:var(--accent);box-shadow:0 0 0 4px var(--bg),0 0 0 6px color-mix(in srgb,var(--accent) 30%,transparent)}',
    '.risk-timeline-when{font-family:var(--fm);font-size:10px;letter-spacing:2px;text-transform:uppercase;color:var(--accent);margin-bottom:8px}',
    '.risk-timeline-name{font-family:var(--fh);font-weight:800;font-size:14px;text-transform:uppercase;letter-spacing:.5px;line-height:1.2;margin-bottom:6px}',
    '.risk-timeline-mit{font-size:12px;line-height:1.5;opacity:.6}',
    '.risk-narr{display:flex;flex-direction:column;gap:14px;margin-top:32px;max-width:820px}',
    '.risk-narr-card{background:var(--surface);border:1px solid var(--wire);border-left:3px solid var(--accent);border-radius:14px;padding:22px 26px}',
    '.risk-narr-q{font-family:var(--fh);font-weight:800;font-size:18px;text-transform:uppercase;letter-spacing:.5px;color:var(--accent);margin-bottom:12px;font-style:italic}',
    '.risk-narr-a{font-size:14px;line-height:1.6;opacity:.85}',
    /* ───── STYLE AXES — algorithmic visual variation system ─────
       Each axis class on #deck cascades into every card/stat/num/bg.
       The cartesian product gives 675 distinct visual combinations
       per layout (×48 layouts = ~32k unique appearances). */
    /* ─ Axis: card-finish (filled / outlined / minimal) ─ */
    '#deck.axis-card-filled .prob-card,#deck.axis-card-filled .fix-check,#deck.axis-card-filled .how-step,#deck.axis-card-filled .stat,#deck.axis-card-filled .val-side-stat,#deck.axis-card-filled .cust-arch-card,#deck.axis-card-filled .team-card,#deck.axis-card-filled .ms-stop > div,#deck.axis-card-filled .fix-pillar,#deck.axis-card-filled .sit-triple-card,#deck.axis-card-filled .imp-cost-mult,#deck.axis-card-filled .risk-narr-card{background:var(--surface);border-color:var(--wire)}',
    '#deck.axis-card-outlined .prob-card,#deck.axis-card-outlined .fix-check,#deck.axis-card-outlined .how-step,#deck.axis-card-outlined .stat,#deck.axis-card-outlined .val-side-stat,#deck.axis-card-outlined .cust-arch-card,#deck.axis-card-outlined .team-card,#deck.axis-card-outlined .fix-pillar,#deck.axis-card-outlined .sit-triple-card,#deck.axis-card-outlined .imp-cost-mult,#deck.axis-card-outlined .risk-narr-card{background:transparent;border:1.5px solid var(--accent);border-opacity:.4}',
    '#deck.axis-card-minimal .prob-card,#deck.axis-card-minimal .fix-check,#deck.axis-card-minimal .how-step,#deck.axis-card-minimal .stat,#deck.axis-card-minimal .val-side-stat,#deck.axis-card-minimal .cust-arch-card,#deck.axis-card-minimal .team-card,#deck.axis-card-minimal .fix-pillar,#deck.axis-card-minimal .sit-triple-card,#deck.axis-card-minimal .imp-cost-mult,#deck.axis-card-minimal .risk-narr-card{background:transparent;border:none;border-top:1px solid var(--wire);border-radius:0;padding-left:0;padding-right:0}',
    /* ─ Axis: accent-fx (where the accent stripe lives) ─ */
    '#deck.axis-accent-bar-top .prob-card,#deck.axis-accent-bar-top .how-step,#deck.axis-accent-bar-top .cust-arch-card,#deck.axis-accent-bar-top .sit-triple-card,#deck.axis-accent-bar-top .fix-pillar{border-top:3px solid var(--accent);border-left:none}',
    '#deck.axis-accent-bar-top .prob-card::before,#deck.axis-accent-bar-top .cust-arch-card::before{display:none}',
    '#deck.axis-accent-bar-left .prob-card,#deck.axis-accent-bar-left .how-step,#deck.axis-accent-bar-left .cust-arch-card,#deck.axis-accent-bar-left .sit-triple-card,#deck.axis-accent-bar-left .fix-pillar{border-left:3px solid var(--accent)}',
    '#deck.axis-accent-bar-left .prob-card::before{display:none}',
    '#deck.axis-accent-underline .prob-head,#deck.axis-accent-underline .how-head,#deck.axis-accent-underline .cust-arch-name,#deck.axis-accent-underline .sit-triple-name,#deck.axis-accent-underline .fix-pillar-name{text-decoration:underline;text-decoration-color:var(--accent);text-decoration-thickness:3px;text-underline-offset:6px}',
    '#deck.axis-accent-glow .prob-card,#deck.axis-accent-glow .how-step,#deck.axis-accent-glow .stat,#deck.axis-accent-glow .cust-arch-card,#deck.axis-accent-glow .team-card,#deck.axis-accent-glow .sit-triple-card,#deck.axis-accent-glow .fix-pillar,#deck.axis-accent-glow .imp-cost-mult{box-shadow:0 0 0 1px color-mix(in srgb,var(--accent) 25%,transparent),0 12px 40px -8px color-mix(in srgb,var(--accent) 35%,transparent)}',
    '#deck.axis-accent-none .prob-card::before,#deck.axis-accent-none .cust-arch-card::before{display:none}',
    '#deck.axis-accent-none .prob-card,#deck.axis-accent-none .how-step,#deck.axis-accent-none .cust-arch-card,#deck.axis-accent-none .sit-triple-card,#deck.axis-accent-none .fix-pillar{border-left:1px solid var(--wire);border-top:1px solid var(--wire)}',
    /* ─ Axis: num-fx (how slide numbers + ordinals render) ─ */
    '#deck.axis-num-italic-display .prob-num,#deck.axis-num-italic-display .how-num,#deck.axis-num-italic-display .cust-arch-num,#deck.axis-num-italic-display .sit-triple-num,#deck.axis-num-italic-display .stat-val,#deck.axis-num-italic-display .val-hero-num,#deck.axis-num-italic-display .val-side-num,#deck.axis-num-italic-display .imp-cost-num,#deck.axis-num-italic-display .cap-val,#deck.axis-num-italic-display .mkt-vertical-size{font-style:italic;font-family:var(--fh)}',
    '#deck.axis-num-mono-tabular .prob-num,#deck.axis-num-mono-tabular .how-num,#deck.axis-num-mono-tabular .cust-arch-num,#deck.axis-num-mono-tabular .sit-triple-num,#deck.axis-num-mono-tabular .stat-val,#deck.axis-num-mono-tabular .val-hero-num,#deck.axis-num-mono-tabular .val-side-num,#deck.axis-num-mono-tabular .imp-cost-num,#deck.axis-num-mono-tabular .cap-val,#deck.axis-num-mono-tabular .mkt-vertical-size{font-family:var(--fm);font-style:normal;letter-spacing:-0.02em;font-variant-numeric:tabular-nums}',
    '#deck.axis-num-circle-badge .prob-num,#deck.axis-num-circle-badge .how-num,#deck.axis-num-circle-badge .cust-arch-num,#deck.axis-num-circle-badge .sit-triple-num{display:inline-flex;align-items:center;justify-content:center;width:48px;height:48px;border-radius:50%;background:var(--accent);color:var(--bg);font-size:18px;font-style:normal;line-height:1}',
    /* ─ Axis: bg-motif (slide background pattern) ─ */
    '#deck.axis-bg-plain .slide-grid{display:none}',
    '#deck.axis-bg-grid .slide-grid{background-image:linear-gradient(var(--wire) 1px,transparent 1px),linear-gradient(90deg,var(--wire) 1px,transparent 1px);background-size:64px 64px;opacity:.32}',
    '#deck.axis-bg-noise .slide{background-image:url("data:image/svg+xml,%3Csvg viewBox=\'0 0 200 200\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cfilter id=\'n2\'%3E%3CfeTurbulence type=\'fractalNoise\' baseFrequency=\'.8\' numOctaves=\'3\'/%3E%3C/filter%3E%3Crect width=\'100%25\' height=\'100%25\' filter=\'url(%23n2)\' opacity=\'.05\'/%3E%3C/svg%3E");background-blend-mode:overlay}',
    '#deck.axis-bg-gradient .slide-bg{background:radial-gradient(ellipse 90% 70% at var(--bgx,50%) var(--bgy,50%),color-mix(in srgb,var(--accent) 20%,transparent) 0%,transparent 65%),radial-gradient(ellipse 60% 50% at calc(100% - var(--bgx,50%)) calc(100% - var(--bgy,50%)),color-mix(in srgb,var(--accent) 12%,transparent) 0%,transparent 60%)}',
    '#deck.axis-bg-dot-grid .slide-grid{background-image:radial-gradient(var(--wire) 1.5px,transparent 1.5px);background-size:28px 28px;background-position:0 0;opacity:.45}',
    /* ─ Axis: density (spacing scale of inner content) ─ */
    '#deck.axis-density-tight .slide-inner{padding:clamp(28px,5vw,72px)}',
    '#deck.axis-density-tight .prob-grid,#deck.axis-density-tight .fix-row,#deck.axis-density-tight .how-flow,#deck.axis-density-tight .stats,#deck.axis-density-tight .cust-arch,#deck.axis-density-tight .team-grid,#deck.axis-density-tight .sit-triple,#deck.axis-density-tight .market-grid,#deck.axis-density-tight .fix-pillars{gap:12px}',
    '#deck.axis-density-spacious .slide-inner{padding:clamp(56px,10vw,140px)}',
    '#deck.axis-density-spacious .prob-grid,#deck.axis-density-spacious .fix-row,#deck.axis-density-spacious .how-flow,#deck.axis-density-spacious .stats,#deck.axis-density-spacious .cust-arch,#deck.axis-density-spacious .team-grid,#deck.axis-density-spacious .sit-triple,#deck.axis-density-spacious .market-grid,#deck.axis-density-spacious .fix-pillars{gap:32px}',
    '#deck.axis-density-spacious .slide-title{margin-bottom:36px}',
    '#deck.axis-density-spacious .slide-sub{margin-bottom:32px}',
  ].join('\n')

  const js = [
    '(function(){',
    "  var deck=document.getElementById('deck');",
    "  var slides=Array.from(document.querySelectorAll('.slide'));",
    "  var dots=Array.from(document.querySelectorAll('#dot-nav button'));",
    "  var counter=document.getElementById('hud-counter');",
    "  var bar=document.getElementById('progress-bar');",
    "  var lbl=document.getElementById('hud-label');",
    '  var total=slides.length;',
    '  var current=0;',
    "  function goTo(idx){if(idx<0||idx>=total)return;slides[idx].scrollIntoView({behavior:'smooth'});}",
    '  var obs=new IntersectionObserver(function(entries){',
    '    entries.forEach(function(entry){',
    '      var sl=entry.target;',
    "      var idx=parseInt(sl.dataset.idx||'0',10);",
    '      if(entry.isIntersecting){',
    "        sl.classList.add('in-view');",
    "        sl.classList.remove('out-above','out-below');",
    '        current=idx;',
    "        dots.forEach(function(d,i){d.classList.toggle('active',i===idx);});",
    "        if(counter)counter.textContent=('0'+(idx+1)).slice(-2)+' / '+('0'+total).slice(-2);",
    "        if(bar)bar.style.width=((idx+1)/total*100)+'%';",
    "        if(lbl)lbl.textContent=sl.dataset.label||'';",
    '      }else{',
    "        sl.classList.remove('in-view');",
    '        var rect=entry.boundingClientRect;',
    "        if(rect.top<0){sl.classList.add('out-above');sl.classList.remove('out-below');}",
    "        else{sl.classList.add('out-below');sl.classList.remove('out-above');}",
    '      }',
    '    });',
    '  },{threshold:0.5,root:deck});',
    '  slides.forEach(function(s){obs.observe(s);});',
    "  dots.forEach(function(d,i){d.addEventListener('click',function(){goTo(i);});});",
    "  document.addEventListener('keydown',function(e){",
    "    if(e.key==='ArrowDown'||e.key==='PageDown'){e.preventDefault();goTo(current+1);}",
    "    if(e.key==='ArrowUp'||e.key==='PageUp'){e.preventDefault();goTo(current-1);}",
    "    if(e.key==='Home'){e.preventDefault();goTo(0);}",
    "    if(e.key==='End'){e.preventDefault();goTo(total-1);}",
    '  });',
    '  var tsy=0;',
    "  deck.addEventListener('touchstart',function(e){tsy=e.touches[0].clientY;},{passive:true});",
    "  deck.addEventListener('touchend',function(e){var dy=tsy-e.changedTouches[0].clientY;if(Math.abs(dy)>50)goTo(dy>0?current+1:current-1);});",
    '  goTo(0);',
    '  // ─── VIEWERSHIP TRACKING ──────────────────────────────────────────',
    '  // Beacon to the SignalDeck app so the founder sees who opened, what',
    '  // they viewed, how long, and whether they reached the end.',
    "  var DECK_ID = " + JSON.stringify(v.deckId || '') + ";",
    "  var TRACK_URL = " + JSON.stringify(v.trackUrl || 'https://signaldeck-two.vercel.app/api/track') + ";",
    '  if (DECK_ID && TRACK_URL) {',
    '    var sessionId = null;',
    '    try { sessionId = localStorage.getItem("__sd_sid"); } catch(e){}',
    '    if (!sessionId) {',
    '      sessionId = (crypto && crypto.randomUUID) ? crypto.randomUUID() : (Date.now() + "-" + Math.random().toString(36).slice(2,10));',
    '      try { localStorage.setItem("__sd_sid", sessionId); } catch(e){}',
    '    }',
    '    var slideStartTs = {};',
    '    function beacon(payload) {',
    '      payload.deckId = DECK_ID; payload.sessionId = sessionId;',
    '      try {',
    '        var body = JSON.stringify(payload);',
    '        if (navigator.sendBeacon) navigator.sendBeacon(TRACK_URL, new Blob([body], {type: "application/json"}));',
    '        else fetch(TRACK_URL, {method:"POST",headers:{"Content-Type":"application/json"},body:body,keepalive:true}).catch(function(){});',
    '      } catch(e){}',
    '    }',
    '    // Open beacon — one per session per deck load',
    '    beacon({event:"open"});',
    '    // Wrap the existing observer behaviour with slide-view/-leave beacons',
    '    var prevSlide = -1;',
    '    var trackObs = new IntersectionObserver(function(entries){',
    '      entries.forEach(function(e){',
    '        var idx = parseInt(e.target.dataset.idx || "0", 10);',
    '        var label = e.target.dataset.label || "";',
    '        if (e.isIntersecting) {',
    '          slideStartTs[idx] = Date.now();',
    '          beacon({event:"slide-view", slideIdx: idx, slideLabel: label});',
    '          if (idx === total - 1) beacon({event:"reached-end", slideIdx: idx});',
    '          prevSlide = idx;',
    '        } else if (slideStartTs[idx]) {',
    '          var dur = Date.now() - slideStartTs[idx];',
    '          delete slideStartTs[idx];',
    '          if (dur > 200) beacon({event:"slide-leave", slideIdx: idx, slideLabel: label, durationMs: dur});',
    '        }',
    '      });',
    '    }, {threshold: 0.5, root: deck});',
    '    slides.forEach(function(s){ trackObs.observe(s); });',
    '    // Close beacon on page exit (sendBeacon survives navigation)',
    '    window.addEventListener("beforeunload", function(){ beacon({event:"close"}); });',
    '    document.addEventListener("visibilitychange", function(){',
    '      if (document.visibilityState === "hidden") {',
    '        if (prevSlide >= 0 && slideStartTs[prevSlide]) {',
    '          var dur = Date.now() - slideStartTs[prevSlide];',
    '          if (dur > 200) beacon({event:"slide-leave", slideIdx: prevSlide, durationMs: dur});',
    '        }',
    '      }',
    '    });',
    '  }',
    '  // Custom cursor (desktop only) — mirrors the reference deck\'s ring+dot pattern.',
    '  if(window.matchMedia&&window.matchMedia("(hover:hover)").matches&&window.matchMedia("(min-width:901px)").matches){',
    '    var cur=document.querySelector(".cursor");var dot=document.querySelector(".cursor-dot");',
    '    if(cur&&dot){',
    '      var mx=0,my=0,cx=0,cy=0;',
    '      document.addEventListener("mousemove",function(e){mx=e.clientX;my=e.clientY;dot.style.transform="translate("+mx+"px,"+my+"px) translate(-50%,-50%)";},{passive:true});',
    '      function tick(){cx+=(mx-cx)*.18;cy+=(my-cy)*.18;cur.style.transform="translate("+cx+"px,"+cy+"px) translate(-50%,-50%)";requestAnimationFrame(tick);}',
    '      tick();',
    '      document.querySelectorAll("a,button,[role=button]").forEach(function(el){',
    '        el.addEventListener("mouseenter",function(){cur.classList.add("hov");});',
    '        el.addEventListener("mouseleave",function(){cur.classList.remove("hov");});',
    '      });',
    '    }',
    '  }',
    '})();',
  ].join('\n')

  return '<!DOCTYPE html>\n' +
    '<html lang="en">\n' +
    '<head>\n' +
    '<meta charset="UTF-8"/>\n' +
    '<meta name="viewport" content="width=device-width,initial-scale=1"/>\n' +
    '<title>' + v.company + '</title>\n' +
    '<link rel="preconnect" href="https://fonts.googleapis.com"/>\n' +
    '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>\n' +
    '<link href="https://fonts.googleapis.com/css2?family=' + fonts + '&display=swap" rel="stylesheet"/>\n' +
    '<style>\n' + css + '\n</style>\n' +
    '</head>\n' +
    '<body>\n' +
    '<div class="cursor"></div><div class="cursor-dot"></div>\n' +
    '<div id="hud">\n' +
    '  <div id="progress-bar"></div>\n' +
    '  <div id="hud-top">\n' +
    '    <span id="hud-company">' + v.company + '</span>\n' +
    '    <span id="hud-counter">01 / ' + total2 + '</span>\n' +
    '  </div>\n' +
    '  <nav id="dot-nav">' + v.dotNav + '</nav>\n' +
    '  <div id="hud-label"></div>\n' +
    '</div>\n' +
    '<div id="deck" class="' + (v.axisClasses || '') + '">' + v.slidesHtml + '</div>\n' +
    '<script>\n' + js + '\n</script>\n' +
    '</body>\n' +
    '</html>'
}
