import { Framework } from './types'

/**
 * Dark-tier tactics. Opt-in only. Never appear by default.
 * These work but they carry real reputation risk. Use deliberately.
 */
export const DARK_FRAMEWORKS: Framework[] = [
  {
    id: 'ad-hominem', name: 'Ad Hominem (vs Competitor)',
    summary: "Attack the competitor's credibility, not just their product.",
    steps: ['Name them','Surface the flaw','Discredit','Pivot to us'],
    when: 'High-conviction competitive slides — only when the criticism is factual.',
    tier: 'dark', category: 'fallacy',
    tags: ['attack','competitor','credibility','negative'],
    bestFor: { industries:['Fintech','Enterprise','SaaS'], stages:['Series A','Series B+'], audiences:['Series A','Strategic'] },
    pairsWith: ['contrast','david-goliath','straw-man'],
    swapAlternatives: ['risk','challenger'],
    risk: 'high',
  },
  {
    id: 'loaded-premise', name: 'Loaded Premise',
    summary: 'Embed your conclusion in the question — "given that legacy fails, how soon do you act?"',
    steps: ['The hidden claim','The forced question','The expected answer','The pivot'],
    when: 'Discovery slides where you can shape the frame.',
    tier: 'dark', category: 'fallacy',
    tags: ['frame','question','manipulation','premise'],
    bestFor: { industries:['Enterprise','Fintech'], stages:['Series A','Series B+'], audiences:['Series A','Strategic'] },
    pairsWith: ['framing','straw-man'],
    swapAlternatives: ['conceptual-selling','solution-selling'],
    risk: 'high',
  },
  {
    id: 'false-dichotomy', name: 'False Dichotomy',
    summary: 'Reduce the world to two options — yours and a strawman.',
    steps: ['Option A (us)','Option B (bad)','No third','Force choice'],
    when: '"Build vs buy us" framing and competitive slides.',
    tier: 'dark', category: 'fallacy',
    tags: ['binary','choice','frame','manipulation'],
    bestFor: { industries:['Enterprise','SaaS','Fintech'], stages:['Seed','Series A'], audiences:['Series A','Strategic'] },
    pairsWith: ['decoy','contrast','loaded-premise'],
    swapAlternatives: ['challenger','solution-selling'],
    risk: 'high',
  },
  {
    id: 'straw-man', name: 'Straw-Man-Then-Knock',
    summary: 'Recast the competitor as a weaker version of themselves — then knock the weaker version.',
    steps: ['Misrepresent them','Easy critique','Knock','Plant doubt'],
    when: 'Late-stage competitive slides where investors are doing diligence.',
    tier: 'dark', category: 'fallacy',
    tags: ['competitor','distort','attack','manipulation'],
    bestFor: { industries:['SaaS','Enterprise','Fintech'], stages:['Series A','Series B+'], audiences:['Series A','Strategic'] },
    pairsWith: ['ad-hominem','false-dichotomy','contrast'],
    swapAlternatives: ['risk','challenger'],
    risk: 'high',
  },
  {
    id: 'dark-scarcity', name: 'Manufactured Scarcity',
    summary: '"Only two allocation slots left" — even if it is not really true.',
    steps: ['Fake limit','Pseudo-evidence','Deadline','Close'],
    when: 'NEVER if false. Listed here so you can recognize it being used on you.',
    tier: 'dark', category: 'fallacy',
    tags: ['urgency','fake','scarcity','manipulation'],
    bestFor: { industries: [], stages:[], audiences:[] },
    pairsWith: ['fomo','term-sheet-anchor'],
    swapAlternatives: ['scarcity'],
    risk: 'high',
  },
  {
    id: 'slippery-slope', name: 'Slippery Slope',
    summary: '"If you do not act now, here is the catastrophic chain that follows."',
    steps: ['Today\'s choice','First fall','Cascade','Bottom'],
    when: 'Risk slides — only when the chain is real.',
    tier: 'dark', category: 'fallacy',
    tags: ['fear','cascade','catastrophe','manipulation'],
    bestFor: { industries:['Fintech','Health','Enterprise'], stages:['Series A','Series B+'], audiences:['Strategic','Series A'] },
    pairsWith: ['loss-aversion','appeal-fear'],
    swapAlternatives: ['risk','loss-aversion'],
    risk: 'high',
  },
  {
    id: 'appeal-fear', name: 'Appeal to Fear (Existential)',
    summary: 'Make the cost of inaction feel like extinction.',
    steps: ['Threat','Closer threat','Personal threat','Exit'],
    when: 'Security, compliance, and existential-risk decks.',
    tier: 'dark', category: 'fallacy',
    tags: ['fear','threat','existential','manipulation'],
    bestFor: { industries:['Fintech','Health','Enterprise','Climate'], stages:['Series A','Series B+'], audiences:['Strategic','Series A'] },
    pairsWith: ['loss-aversion','slippery-slope','pas'],
    swapAlternatives: ['risk','loss-aversion'],
    risk: 'high',
  },
  {
    id: 'appeal-vanity', name: 'Appeal to Vanity',
    summary: '"Smart investors like you already see this." Flatter the ego.',
    steps: ['Compliment','Implied club','Confirmation','Ask'],
    when: 'Warm rooms with ego-driven counterparts.',
    tier: 'dark', category: 'fallacy',
    tags: ['ego','flattery','vanity','manipulation'],
    bestFor: { industries: ALL(), stages:['Seed','Series A'], audiences:['Angel','Seed VC'] },
    pairsWith: ['liking','social-proof','unity'],
    swapAlternatives: ['liking'],
    risk: 'high',
  },
  {
    id: 'manufactured-urgency', name: 'Manufactured Urgency',
    summary: 'Invented deadlines, fake closing windows, theatrical FOMO.',
    steps: ['Set the clock','Tick','Press','Close'],
    when: 'NEVER if false. Listed for awareness — easy way to lose trust permanently.',
    tier: 'dark', category: 'fallacy',
    tags: ['urgency','fake','pressure','manipulation'],
    bestFor: { industries: [], stages:[], audiences:[] },
    pairsWith: ['fomo','dark-scarcity'],
    swapAlternatives: ['scarcity','fomo'],
    risk: 'high',
  },
  {
    id: 'reciprocal-trap', name: 'Reciprocal Trap',
    summary: 'Give an unsolicited "favor" so the counterpart feels obligated to reciprocate beyond its value.',
    steps: ['Unsolicited gift','Implied debt','The ask','Cash in'],
    when: 'Negotiations where the counterpart cares about social debts.',
    tier: 'dark', category: 'fallacy',
    tags: ['reciprocity','debt','obligation','manipulation'],
    bestFor: { industries: ALL(), stages:['Seed','Series A'], audiences:['Strategic','Angel'] },
    pairsWith: ['reciprocity','commitment'],
    swapAlternatives: ['reciprocity'],
    risk: 'high',
  },
]

function ALL() {
  return ['Fintech','SaaS','AI','Enterprise','Consumer','Developer Tools','Climate','Health','Education','Other']
}
