import { Framework } from './types'

const ALL_INDUSTRIES = ['Fintech','SaaS','AI','Enterprise','Consumer','Developer Tools','Climate','Health','Education','Other']
const ALL_STAGES = ['Pre-seed','Seed','Series A','Series B+','Bootstrapped']
const ALL_AUDIENCES = ['Seed VC','Series A','Angel','Strategic','Internal']

export const FRAMEWORKS: Framework[] = [
  // ── Original 6 (kept verbatim, now with metadata) ───────────────────────
  {
    id: 'spin', name: 'SPIN Selling',
    summary: 'Diagnose pain before pitching the cure.',
    steps: ['Situation','Problem','Implication','Need-payoff'],
    when: 'Enterprise / long sales cycle decks.',
    tier: 'clean', category: 'sales-framework',
    tags: ['discovery','pain','enterprise','logic'],
    bestFor: { industries:['Enterprise','SaaS','Developer Tools'], stages:['Series A','Series B+'], audiences:['Series A','Strategic'] },
    pairsWith: ['risk','meddic','value-selling'],
    swapAlternatives: ['challenger','solution-selling','pas'],
    risk: 'low',
  },
  {
    id: 'belief', name: 'Belief Chain',
    summary: 'Stack the beliefs the investor must accept, in order.',
    steps: ['World is changing','Old way breaks','New way wins','We are the new way'],
    when: 'Category-creation pitches.',
    tier: 'clean', category: 'narrative-frame',
    tags: ['inevitability','vision','category','logic'],
    bestFor: { industries:['AI','Climate','Consumer'], stages:['Seed','Series A'], audiences:['Seed VC','Series A'] },
    pairsWith: ['cat','inevitability','why-now'],
    swapAlternatives: ['hero-journey','tailwind','founder-market-fit'],
    risk: 'low',
  },
  {
    id: 'risk', name: 'Risk Reversal',
    summary: 'Surface the obvious risk and dismantle it.',
    steps: ['Name the risk','Quantify it','Show our hedge','Show proof'],
    when: 'Skeptical / late-stage investors.',
    tier: 'clean', category: 'sales-framework',
    tags: ['objections','proof','trust','late-stage'],
    bestFor: { industries:['Fintech','Health','Enterprise'], stages:['Series A','Series B+'], audiences:['Series A','Strategic'] },
    pairsWith: ['meddic','social-proof','authority'],
    swapAlternatives: ['challenger','value-selling'],
    risk: 'low',
  },
  {
    id: 'cat', name: 'Category Creation',
    summary: 'Define a new game where you are already winning.',
    steps: ['Old category','New category','Stakes','Frontier metric'],
    when: 'Market-defining pitches.',
    tier: 'clean', category: 'narrative-frame',
    tags: ['category','vision','inevitability','frontier'],
    bestFor: { industries:['AI','Consumer','Climate'], stages:['Seed','Series A'], audiences:['Seed VC','Series A'] },
    pairsWith: ['belief','inevitability','tailwind'],
    swapAlternatives: ['hero-journey','david-goliath'],
    risk: 'medium',
  },
  {
    id: 'jtbd', name: 'Jobs To Be Done',
    summary: 'Frame the customer hire, not the customer profile.',
    steps: ['Job','Hire','Fire','Outcome'],
    when: 'Consumer / horizontal products.',
    tier: 'clean', category: 'sales-framework',
    tags: ['customer','outcome','horizontal','consumer'],
    bestFor: { industries:['Consumer','SaaS','Developer Tools'], stages:['Pre-seed','Seed'], audiences:['Seed VC','Angel'] },
    pairsWith: ['pas','bab','value-selling'],
    swapAlternatives: ['spin','solution-selling'],
    risk: 'low',
  },
  {
    id: 'bab', name: 'Before-After-Bridge',
    summary: 'Paint pain, paint relief, name the bridge.',
    steps: ['Before','After','Bridge','Proof'],
    when: 'Short / demo-led decks.',
    tier: 'clean', category: 'sales-framework',
    tags: ['demo','contrast','pain','transformation'],
    bestFor: { industries:['Consumer','SaaS','Developer Tools'], stages:['Pre-seed','Seed'], audiences:['Seed VC','Angel'] },
    pairsWith: ['pas','jtbd','contrast'],
    swapAlternatives: ['aida','fab','4ps'],
    risk: 'low',
  },

  // ── Clean tier: classic sales frameworks ────────────────────────────────
  {
    id: 'snap', name: 'SNAP Selling',
    summary: 'Win the time-starved buyer with simple, valuable, aligned, priority pitches.',
    steps: ['Simple','iNvaluable','Aligned','Priority'],
    when: 'Selling to overwhelmed execs with short attention.',
    tier: 'clean', category: 'sales-framework',
    tags: ['speed','clarity','executive','priority'],
    bestFor: { industries:['Enterprise','SaaS'], stages:['Seed','Series A'], audiences:['Strategic','Series A'] },
    pairsWith: ['challenger','value-selling'],
    swapAlternatives: ['spin','solution-selling','meddic'],
    risk: 'low',
  },
  {
    id: 'sandler', name: 'Sandler Submarine',
    summary: 'Qualify hard before you sell — let prospects disqualify themselves.',
    steps: ['Bonding & rapport','Pain','Budget','Decision'],
    when: 'High-ticket sales where wasted cycles are expensive.',
    tier: 'clean', category: 'sales-framework',
    tags: ['qualification','pain','budget','enterprise'],
    bestFor: { industries:['Enterprise','SaaS'], stages:['Series A','Series B+'], audiences:['Series A','Strategic'] },
    pairsWith: ['meddic','spin'],
    swapAlternatives: ['challenger','value-selling','snap'],
    risk: 'low',
  },
  {
    id: 'challenger', name: 'Challenger Sale',
    summary: 'Teach, tailor, and take control — reframe the buyer’s worldview.',
    steps: ['Warmer','Reframe','Rational drowning','Emotional impact'],
    when: 'Complex B2B sales where the buyer thinks they know the answer.',
    tier: 'clean', category: 'sales-framework',
    tags: ['reframe','authority','teach','enterprise'],
    bestFor: { industries:['Enterprise','SaaS','Fintech'], stages:['Series A','Series B+'], audiences:['Series A','Strategic'] },
    pairsWith: ['authority','belief','risk'],
    swapAlternatives: ['spin','snap','solution-selling'],
    risk: 'medium',
  },
  {
    id: 'meddic', name: 'MEDDIC',
    summary: 'Qualify the deal: Metrics, Economic buyer, Decision criteria, Decision process, Identify pain, Champion.',
    steps: ['Metrics','Economic buyer','Decision process','Champion'],
    when: 'Enterprise sales with multiple stakeholders.',
    tier: 'clean', category: 'sales-framework',
    tags: ['enterprise','qualification','metrics','champion'],
    bestFor: { industries:['Enterprise','SaaS','Fintech'], stages:['Series A','Series B+'], audiences:['Series A','Strategic'] },
    pairsWith: ['spin','value-selling','risk'],
    swapAlternatives: ['sandler','challenger'],
    risk: 'low',
  },
  {
    id: 'solution-selling', name: 'Solution Selling',
    summary: 'Diagnose then prescribe — sell the cure, not the pill.',
    steps: ['Diagnose pain','Vision','Value','Control'],
    when: 'Complex products where buyers can’t self-diagnose.',
    tier: 'clean', category: 'sales-framework',
    tags: ['diagnose','vision','value','complex'],
    bestFor: { industries:['Enterprise','SaaS','Health'], stages:['Seed','Series A'], audiences:['Series A','Strategic'] },
    pairsWith: ['spin','jtbd','pas'],
    swapAlternatives: ['challenger','value-selling','snap'],
    risk: 'low',
  },
  {
    id: 'value-selling', name: 'Value Selling',
    summary: 'Quantify the dollar impact, then anchor your ask against it.',
    steps: ['Status quo cost','Future-state value','Delta in dollars','ROI proof'],
    when: 'ROI-sensitive buyers and analytical investors.',
    tier: 'clean', category: 'sales-framework',
    tags: ['roi','quantify','dollars','logic'],
    bestFor: { industries:['Enterprise','SaaS','Fintech'], stages:['Series A','Series B+'], audiences:['Series A','Strategic'] },
    pairsWith: ['meddic','risk','logos'],
    swapAlternatives: ['solution-selling','spin','challenger'],
    risk: 'low',
  },
  {
    id: 'conceptual-selling', name: 'Conceptual Selling',
    summary: 'Sell to the buyer’s concept of the problem, not your product.',
    steps: ['Confirming questions','New info','Attitude','Commitment'],
    when: 'Buyers with strong existing mental models.',
    tier: 'clean', category: 'sales-framework',
    tags: ['mental-model','questions','listening','buyer-led'],
    bestFor: { industries:['Enterprise','Consumer','Health'], stages:['Seed','Series A'], audiences:['Seed VC','Strategic'] },
    pairsWith: ['jtbd','pathos','liking'],
    swapAlternatives: ['solution-selling','spin'],
    risk: 'low',
  },
  {
    id: 'aida', name: 'AIDA',
    summary: 'Attention → Interest → Desire → Action. The oldest funnel still works.',
    steps: ['Attention','Interest','Desire','Action'],
    when: 'Cold outreach, landing pages, demo-led decks.',
    tier: 'clean', category: 'sales-framework',
    tags: ['funnel','attention','classic','demo'],
    bestFor: { industries:['Consumer','SaaS','Education'], stages:['Pre-seed','Seed'], audiences:['Seed VC','Angel'] },
    pairsWith: ['bab','pas','pattern-interrupt'],
    swapAlternatives: ['fab','4ps','jtbd'],
    risk: 'low',
  },
  {
    id: 'pas', name: 'Pain-Agitate-Solution',
    summary: 'Find the pain, twist the knife, then deliver the cure.',
    steps: ['Pain','Agitate','Solution','Proof'],
    when: 'Direct response, cold pitches, problem-led decks.',
    tier: 'clean', category: 'sales-framework',
    tags: ['pain','urgency','direct-response','emotional'],
    bestFor: { industries:['Consumer','SaaS','Health'], stages:['Pre-seed','Seed'], audiences:['Seed VC','Angel'] },
    pairsWith: ['bab','jtbd','loss-aversion'],
    swapAlternatives: ['aida','fab','spin'],
    risk: 'medium',
  },
  {
    id: 'fab', name: 'Features-Advantages-Benefits',
    summary: 'Turn dry features into vivid buyer outcomes.',
    steps: ['Feature','Advantage','Benefit','Proof'],
    when: 'Product-led decks and demo walkthroughs.',
    tier: 'clean', category: 'sales-framework',
    tags: ['product','demo','benefit','classic'],
    bestFor: { industries:['SaaS','Developer Tools','Consumer'], stages:['Pre-seed','Seed'], audiences:['Seed VC','Angel'] },
    pairsWith: ['bab','aida','jtbd'],
    swapAlternatives: ['4ps','pas','solution-selling'],
    risk: 'low',
  },
  {
    id: '4ps', name: '4 Ps (Picture-Promise-Prove-Push)',
    summary: 'Paint the picture, make the promise, prove it, push the close.',
    steps: ['Picture','Promise','Prove','Push'],
    when: 'Short-form persuasion, landing pages, one-pagers.',
    tier: 'clean', category: 'sales-framework',
    tags: ['short-form','promise','push','close'],
    bestFor: { industries:['Consumer','SaaS','Education'], stages:['Pre-seed','Seed'], audiences:['Seed VC','Angel'] },
    pairsWith: ['aida','bab','pattern-interrupt'],
    swapAlternatives: ['fab','pas','jtbd'],
    risk: 'low',
  },

  // ── Clean tier: Cialdini's 7 principles ─────────────────────────────────
  {
    id: 'reciprocity', name: 'Reciprocity',
    summary: 'Give first — value, insight, access — then ask.',
    steps: ['Give','Show','Anchor the gift','Ask'],
    when: 'Cold investor outreach and partnership pitches.',
    tier: 'clean', category: 'persuasion-principle',
    tags: ['give-first','rapport','generosity','cialdini'],
    bestFor: { industries: ALL_INDUSTRIES, stages:['Pre-seed','Seed'], audiences:['Angel','Seed VC','Strategic'] },
    pairsWith: ['liking','authority','social-proof'],
    swapAlternatives: ['unity','commitment'],
    risk: 'low',
  },
  {
    id: 'commitment', name: 'Commitment & Consistency',
    summary: 'Get a small yes, then escalate — people stay consistent with prior commitments.',
    steps: ['Tiny ask','Public yes','Mid ask','Big ask'],
    when: 'Building investor warmth over multiple touchpoints.',
    tier: 'clean', category: 'persuasion-principle',
    tags: ['micro-commitment','consistency','cialdini','sequence'],
    bestFor: { industries: ALL_INDUSTRIES, stages:['Pre-seed','Seed','Series A'], audiences:['Seed VC','Angel'] },
    pairsWith: ['foot-in-the-door','reciprocity','social-proof'],
    swapAlternatives: ['unity','authority'],
    risk: 'low',
  },
  {
    id: 'social-proof', name: 'Social Proof',
    summary: 'Show that smart people already trust you.',
    steps: ['Logos','Quotes','Numbers','Names'],
    when: 'Any deck — but disproportionately powerful with skeptical investors.',
    tier: 'clean', category: 'persuasion-principle',
    tags: ['validation','logos','customers','cialdini'],
    bestFor: { industries: ALL_INDUSTRIES, stages:['Seed','Series A','Series B+'], audiences:['Seed VC','Series A','Strategic'] },
    pairsWith: ['authority','risk','investor-social-proof'],
    swapAlternatives: ['liking','unity'],
    risk: 'low',
  },
  {
    id: 'authority', name: 'Authority',
    summary: 'Borrow credibility from credentials, names, and visible expertise.',
    steps: ['Credential','Track record','Endorsement','Result'],
    when: 'When the founder or team is the moat.',
    tier: 'clean', category: 'persuasion-principle',
    tags: ['credibility','expertise','team','cialdini'],
    bestFor: { industries:['Fintech','Health','AI','Enterprise'], stages:['Seed','Series A'], audiences:['Seed VC','Series A','Strategic'] },
    pairsWith: ['founder-market-fit','social-proof','ethos'],
    swapAlternatives: ['liking','unity'],
    risk: 'low',
  },
  {
    id: 'liking', name: 'Liking',
    summary: 'People say yes to people they like — mirror, compliment, find common ground.',
    steps: ['Common ground','Genuine compliment','Mirror','Ask'],
    when: 'First-meeting investor pitches and warm intros.',
    tier: 'clean', category: 'persuasion-principle',
    tags: ['rapport','warmth','cialdini','interpersonal'],
    bestFor: { industries: ALL_INDUSTRIES, stages:['Pre-seed','Seed'], audiences:['Angel','Seed VC'] },
    pairsWith: ['reciprocity','unity','pathos'],
    swapAlternatives: ['authority','social-proof'],
    risk: 'low',
  },
  {
    id: 'scarcity', name: 'Scarcity',
    summary: 'Limited round, limited allocation, limited window — fewer makes it more.',
    steps: ['Frame the limit','Show demand','Name the deadline','Open the door'],
    when: 'When the round is competitive and you can honestly show momentum.',
    tier: 'clean', category: 'persuasion-principle',
    tags: ['urgency','exclusivity','round','cialdini'],
    bestFor: { industries: ALL_INDUSTRIES, stages:['Seed','Series A'], audiences:['Seed VC','Series A','Angel'] },
    pairsWith: ['fomo','term-sheet-anchor','social-proof'],
    swapAlternatives: ['authority','inevitability'],
    risk: 'medium',
  },
  {
    id: 'unity', name: 'Unity',
    summary: 'We — same tribe, same mission, same enemy.',
    steps: ['Shared identity','Shared enemy','Shared mission','Shared win'],
    when: 'Mission-driven pitches and aligned-strategic conversations.',
    tier: 'clean', category: 'persuasion-principle',
    tags: ['tribe','mission','we','cialdini'],
    bestFor: { industries:['Climate','Health','AI','Consumer'], stages:['Pre-seed','Seed'], audiences:['Angel','Seed VC','Strategic'] },
    pairsWith: ['liking','pathos','founder-market-fit'],
    swapAlternatives: ['reciprocity','authority'],
    risk: 'low',
  },

  // ── Clean tier: Aristotelian rhetoric ───────────────────────────────────
  {
    id: 'ethos', name: 'Ethos',
    summary: 'Credibility through character — why you, why now, why trusted.',
    steps: ['Position','Proof','Principles','Posture'],
    when: 'When the buyer must trust the speaker before the offer.',
    tier: 'clean', category: 'rhetorical-device',
    tags: ['credibility','character','trust','rhetoric'],
    bestFor: { industries: ALL_INDUSTRIES, stages:['Pre-seed','Seed','Series A'], audiences:['Seed VC','Angel','Series A'] },
    pairsWith: ['authority','founder-market-fit','logos'],
    swapAlternatives: ['pathos','unity'],
    risk: 'low',
  },
  {
    id: 'pathos', name: 'Pathos',
    summary: 'Move them emotionally — stake, story, stakes again.',
    steps: ['Stake','Story','Vivid detail','Stakes again'],
    when: 'Mission-driven, consumer, and founder-led narratives.',
    tier: 'clean', category: 'rhetorical-device',
    tags: ['emotion','story','stakes','rhetoric'],
    bestFor: { industries:['Consumer','Health','Climate','Education'], stages:['Pre-seed','Seed'], audiences:['Angel','Seed VC'] },
    pairsWith: ['hero-journey','unity','liking'],
    swapAlternatives: ['ethos','logos'],
    risk: 'low',
  },
  {
    id: 'logos', name: 'Logos',
    summary: 'Cold logic — numbers, structure, undeniable arithmetic.',
    steps: ['Premise','Evidence','Math','Conclusion'],
    when: 'Analytical investors, late-stage decks, technical buyers.',
    tier: 'clean', category: 'rhetorical-device',
    tags: ['logic','numbers','evidence','rhetoric'],
    bestFor: { industries:['Fintech','Enterprise','SaaS','AI'], stages:['Series A','Series B+'], audiences:['Series A','Strategic'] },
    pairsWith: ['value-selling','meddic','risk'],
    swapAlternatives: ['ethos','pathos'],
    risk: 'low',
  },
  {
    id: 'kairos', name: 'Kairos',
    summary: 'The right thing at the right moment — timing as argument.',
    steps: ['Window','Why now','Cost of waiting','Open the door'],
    when: 'Tailwind-led pitches and post-shift markets.',
    tier: 'clean', category: 'rhetorical-device',
    tags: ['timing','why-now','tailwind','rhetoric'],
    bestFor: { industries:['AI','Climate','Fintech'], stages:['Pre-seed','Seed','Series A'], audiences:['Seed VC','Series A'] },
    pairsWith: ['why-now','tailwind','inevitability'],
    swapAlternatives: ['belief','cat'],
    risk: 'low',
  },

  // ── Clean tier: narrative frames ────────────────────────────────────────
  {
    id: 'hero-journey', name: "Hero's Journey",
    summary: 'Ordinary world → call → trial → return changed. Cast the customer (or founder) as hero.',
    steps: ['Ordinary world','Call to adventure','Trial','Return changed'],
    when: 'Founder-led origin pitches and consumer narratives.',
    tier: 'clean', category: 'narrative-frame',
    tags: ['story','journey','founder','transformation'],
    bestFor: { industries:['Consumer','Health','Education','Climate'], stages:['Pre-seed','Seed'], audiences:['Angel','Seed VC'] },
    pairsWith: ['pathos','founder-market-fit','origin-story'],
    swapAlternatives: ['david-goliath','underdog'],
    risk: 'low',
  },
  {
    id: 'david-goliath', name: 'David vs Goliath',
    summary: 'Name the giant. Name the slingshot. Win because of the asymmetry.',
    steps: ['The giant','Their weakness','Our slingshot','The win'],
    when: 'Competitive markets where incumbents look unassailable.',
    tier: 'clean', category: 'narrative-frame',
    tags: ['underdog','asymmetry','competitor','narrative'],
    bestFor: { industries:['Fintech','SaaS','Consumer'], stages:['Seed','Series A'], audiences:['Seed VC','Series A','Angel'] },
    pairsWith: ['underdog','contrast','pattern-interrupt'],
    swapAlternatives: ['cat','belief','hero-journey'],
    risk: 'low',
  },
  {
    id: 'underdog', name: 'Underdog',
    summary: 'Smaller, faster, hungrier — and that is the point.',
    steps: ['The odds','The grit','The proof','The flip'],
    when: 'Early decks where the team is the asset.',
    tier: 'clean', category: 'narrative-frame',
    tags: ['grit','team','scrappy','narrative'],
    bestFor: { industries: ALL_INDUSTRIES, stages:['Pre-seed','Seed'], audiences:['Angel','Seed VC'] },
    pairsWith: ['david-goliath','founder-market-fit','pathos'],
    swapAlternatives: ['hero-journey','ethos'],
    risk: 'low',
  },
  {
    id: 'founder-market-fit', name: 'Founder–Market Fit',
    summary: 'You are the only person crazy enough — and qualified enough — to do this.',
    steps: ['Unfair insight','Unfair credential','Unfair network','Unfair conviction'],
    when: 'Pre-seed and seed pitches where the founder is the proof.',
    tier: 'clean', category: 'narrative-frame',
    tags: ['founder','insight','credential','conviction'],
    bestFor: { industries: ALL_INDUSTRIES, stages:['Pre-seed','Seed'], audiences:['Angel','Seed VC'] },
    pairsWith: ['origin-story','ethos','authority'],
    swapAlternatives: ['hero-journey','underdog'],
    risk: 'low',
  },
  {
    id: 'origin-story', name: 'Origin Story',
    summary: 'The day you realized this had to exist.',
    steps: ['The day','The pain','The decision','The build'],
    when: 'Warm intros and founder-led pitches.',
    tier: 'clean', category: 'narrative-frame',
    tags: ['origin','founder','story','pathos'],
    bestFor: { industries:['Consumer','Health','Climate','Education'], stages:['Pre-seed','Seed'], audiences:['Angel','Seed VC'] },
    pairsWith: ['hero-journey','founder-market-fit','pathos'],
    swapAlternatives: ['underdog','unity'],
    risk: 'low',
  },
  {
    id: 'inevitability', name: 'Inevitability',
    summary: 'This is happening anyway. We are just the fastest to it.',
    steps: ['Force at work','Direction','Speed','Our position'],
    when: 'Category-creating and tailwind-driven decks.',
    tier: 'clean', category: 'narrative-frame',
    tags: ['inevitability','tailwind','vision','category'],
    bestFor: { industries:['AI','Climate','Fintech'], stages:['Seed','Series A'], audiences:['Seed VC','Series A'] },
    pairsWith: ['belief','cat','kairos'],
    swapAlternatives: ['why-now','tailwind'],
    risk: 'medium',
  },
  {
    id: 'tailwind', name: 'Tailwind Story',
    summary: 'Three forces just lined up — and we are riding all of them.',
    steps: ['Force 1','Force 2','Force 3','Our wedge'],
    when: 'Markets with recent regulatory, technological, or behavioral shifts.',
    tier: 'clean', category: 'narrative-frame',
    tags: ['tailwind','timing','why-now','market'],
    bestFor: { industries:['AI','Climate','Fintech','Health'], stages:['Seed','Series A'], audiences:['Seed VC','Series A'] },
    pairsWith: ['why-now','kairos','inevitability'],
    swapAlternatives: ['belief','cat'],
    risk: 'low',
  },
  {
    id: 'why-now', name: 'Why-Now / Why-Us / Why-This',
    summary: 'Three forced questions, three forced answers.',
    steps: ['Why now','Why us','Why this','Why win'],
    when: 'Every pitch — but especially when the door is closing.',
    tier: 'clean', category: 'narrative-frame',
    tags: ['timing','founder','wedge','classic'],
    bestFor: { industries: ALL_INDUSTRIES, stages:['Pre-seed','Seed','Series A'], audiences:['Seed VC','Series A','Angel'] },
    pairsWith: ['kairos','tailwind','inevitability'],
    swapAlternatives: ['belief','cat'],
    risk: 'low',
  },

  // ── Edgy tier: cognitive-bias plays ─────────────────────────────────────
  {
    id: 'loss-aversion', name: 'Loss Aversion',
    summary: 'Losses hurt 2x more than gains feel good — frame the cost of inaction.',
    steps: ['Status quo','Cost of inaction','Compound loss','Exit door'],
    when: 'Late-stage and risk-sensitive investors.',
    tier: 'edgy', category: 'cognitive-bias',
    tags: ['fear','loss','urgency','prospect-theory'],
    bestFor: { industries:['Fintech','Enterprise','Health'], stages:['Series A','Series B+'], audiences:['Series A','Strategic'] },
    pairsWith: ['risk','pas','fomo'],
    swapAlternatives: ['scarcity','contrast'],
    risk: 'medium',
  },
  {
    id: 'anchoring', name: 'Anchoring',
    summary: 'Drop a big number first — every number after is judged against it.',
    steps: ['Anchor','Justify','Counter-anchor','Land'],
    when: 'Round size, valuation, and TAM conversations.',
    tier: 'edgy', category: 'cognitive-bias',
    tags: ['anchor','number','valuation','negotiation'],
    bestFor: { industries: ALL_INDUSTRIES, stages:['Seed','Series A','Series B+'], audiences:['Seed VC','Series A'] },
    pairsWith: ['term-sheet-anchor','power-law','contrast'],
    swapAlternatives: ['decoy','bracketing'],
    risk: 'medium',
  },
  {
    id: 'bandwagon', name: 'Bandwagon',
    summary: 'Everyone is moving. You do not want to be the last one in.',
    steps: ['The movement','The names','The pace','The seat'],
    when: 'Late round, competitive moment, social-proof-rich situations.',
    tier: 'edgy', category: 'cognitive-bias',
    tags: ['herd','fomo','momentum','social'],
    bestFor: { industries:['AI','Fintech','Consumer'], stages:['Seed','Series A'], audiences:['Seed VC','Series A'] },
    pairsWith: ['fomo','social-proof','investor-social-proof'],
    swapAlternatives: ['scarcity','term-sheet-anchor'],
    risk: 'medium',
  },
  {
    id: 'fomo', name: 'FOMO (Fear of Missing Out)',
    summary: 'Show the door closing — but only if it really is.',
    steps: ['Open door','Who is already in','Closing window','Exit'],
    when: 'Honest momentum moments — never manufactured.',
    tier: 'edgy', category: 'cognitive-bias',
    tags: ['urgency','fear','close','momentum'],
    bestFor: { industries: ALL_INDUSTRIES, stages:['Seed','Series A'], audiences:['Seed VC','Series A','Angel'] },
    pairsWith: ['scarcity','bandwagon','term-sheet-anchor'],
    swapAlternatives: ['loss-aversion','contrast'],
    risk: 'medium',
  },
  {
    id: 'decoy', name: 'Decoy Effect',
    summary: 'Add a worse option to make the middle one look obvious.',
    steps: ['Premium','Decoy','Target','Frame'],
    when: 'Pricing slides and "build vs partner vs buy" comparisons.',
    tier: 'edgy', category: 'cognitive-bias',
    tags: ['pricing','contrast','options','choice'],
    bestFor: { industries:['SaaS','Enterprise','Consumer'], stages:['Seed','Series A'], audiences:['Series A','Strategic'] },
    pairsWith: ['anchoring','contrast','framing'],
    swapAlternatives: ['bracketing','batna'],
    risk: 'medium',
  },
  {
    id: 'contrast', name: 'Contrast Principle',
    summary: 'Show the painful before next to the gleaming after.',
    steps: ['Old world','New world','Side-by-side','Verdict'],
    when: 'Demo-led decks and product comparison slides.',
    tier: 'edgy', category: 'cognitive-bias',
    tags: ['contrast','before-after','demo','clarity'],
    bestFor: { industries: ALL_INDUSTRIES, stages:['Pre-seed','Seed','Series A'], audiences:['Seed VC','Series A'] },
    pairsWith: ['bab','decoy','framing'],
    swapAlternatives: ['pas','aida'],
    risk: 'low',
  },
  {
    id: 'framing', name: 'Gain vs Loss Framing',
    summary: 'Same fact, different framing — 90% survival or 10% mortality.',
    steps: ['Neutral fact','Loss frame','Gain frame','Pick the live one'],
    when: 'Risk slides, pricing, and metrics.',
    tier: 'edgy', category: 'cognitive-bias',
    tags: ['framing','perception','spin','bias'],
    bestFor: { industries: ALL_INDUSTRIES, stages:['Seed','Series A','Series B+'], audiences:['Seed VC','Series A','Strategic'] },
    pairsWith: ['loss-aversion','contrast','anchoring'],
    swapAlternatives: ['decoy','pattern-interrupt'],
    risk: 'medium',
  },
  {
    id: 'pattern-interrupt', name: 'Pattern Interrupt',
    summary: 'Break the expected script — a weird stat, a counter-narrative, a silence.',
    steps: ['Setup the expectation','Break it','Re-engage','Pivot'],
    when: 'Cold opens, first slides, and meetings that have gone stale.',
    tier: 'edgy', category: 'cognitive-bias',
    tags: ['surprise','attention','open','hook'],
    bestFor: { industries:['Consumer','AI','Developer Tools'], stages:['Pre-seed','Seed'], audiences:['Angel','Seed VC'] },
    pairsWith: ['aida','4ps','contrast'],
    swapAlternatives: ['pas','bab'],
    risk: 'low',
  },
  {
    id: 'foot-in-the-door', name: 'Foot-in-the-Door',
    summary: 'Get a small yes now — escalate later.',
    steps: ['Tiny ask','Yes','Mid ask','Big ask'],
    when: 'Long courting cycles with target investors.',
    tier: 'edgy', category: 'cognitive-bias',
    tags: ['micro-commitment','sequence','escalate'],
    bestFor: { industries: ALL_INDUSTRIES, stages:['Pre-seed','Seed'], audiences:['Seed VC','Angel'] },
    pairsWith: ['commitment','reciprocity'],
    swapAlternatives: ['door-in-the-face'],
    risk: 'medium',
  },
  {
    id: 'door-in-the-face', name: 'Door-in-the-Face',
    summary: 'Make a big ask first. The real ask sounds reasonable by comparison.',
    steps: ['Big ask','Pushback','Concession','Real ask'],
    when: 'Negotiation and large strategic conversations.',
    tier: 'edgy', category: 'cognitive-bias',
    tags: ['negotiation','contrast','concession'],
    bestFor: { industries:['Enterprise','Fintech'], stages:['Series A','Series B+'], audiences:['Strategic','Series A'] },
    pairsWith: ['anchoring','batna','contrast'],
    swapAlternatives: ['foot-in-the-door','decoy'],
    risk: 'medium',
  },

  // ── Edgy tier: investor-specific plays ──────────────────────────────────
  {
    id: 'term-sheet-anchor', name: 'Term-Sheet Anchor',
    summary: 'A real term sheet on the table sets the floor for every conversation after.',
    steps: ['Existing TS','Pace of round','Open seats','Deadline'],
    when: 'Only if true. Lying here ends careers.',
    tier: 'edgy', category: 'investor-play',
    tags: ['anchor','round','momentum','urgency'],
    bestFor: { industries: ALL_INDUSTRIES, stages:['Seed','Series A'], audiences:['Seed VC','Series A','Angel'] },
    pairsWith: ['scarcity','fomo','bandwagon'],
    swapAlternatives: ['anchoring','investor-social-proof'],
    risk: 'high',
  },
  {
    id: 'investor-social-proof', name: 'Investor Social Proof',
    summary: 'Name the believers — the right names move the room.',
    steps: ['First check','Lead candidate','Strategic angel','Advisor'],
    when: 'Once you have credible names — never bluff.',
    tier: 'edgy', category: 'investor-play',
    tags: ['credibility','names','round','authority'],
    bestFor: { industries: ALL_INDUSTRIES, stages:['Pre-seed','Seed','Series A'], audiences:['Seed VC','Series A','Angel'] },
    pairsWith: ['social-proof','authority','bandwagon'],
    swapAlternatives: ['scarcity','term-sheet-anchor'],
    risk: 'medium',
  },
  {
    id: 'anti-portfolio-bait', name: 'Anti-Portfolio Bait',
    summary: 'Make it the deal they will regret passing on.',
    steps: ['Their thesis','Our fit','Our trajectory','Their regret'],
    when: 'When you have one specific investor in mind.',
    tier: 'edgy', category: 'investor-play',
    tags: ['regret','targeted','fit','specific'],
    bestFor: { industries: ALL_INDUSTRIES, stages:['Seed','Series A'], audiences:['Seed VC','Series A'] },
    pairsWith: ['founder-market-fit','inevitability','tailwind'],
    swapAlternatives: ['fomo','investor-social-proof'],
    risk: 'medium',
  },
  {
    id: 'power-law', name: 'Power-Law Positioning',
    summary: 'Frame yourself as a fund-returner — not a base hit.',
    steps: ['Fund math','Outlier path','Top-decile signals','Why us'],
    when: 'Speaking to seed/Series A VCs who live by power law.',
    tier: 'edgy', category: 'investor-play',
    tags: ['vc','outlier','fund-returner','math'],
    bestFor: { industries:['AI','Fintech','Consumer','Climate'], stages:['Seed','Series A'], audiences:['Seed VC','Series A'] },
    pairsWith: ['inevitability','cat','logos'],
    swapAlternatives: ['anchoring','tailwind'],
    risk: 'medium',
  },
  {
    id: 'bottom-up-tam', name: 'Bottom-Up TAM',
    summary: 'Skip the "1% of a trillion" trap — build TAM from real customers up.',
    steps: ['ICP','ACV','Reachable count','TAM'],
    when: 'Late-stage and sophisticated investor decks.',
    tier: 'clean', category: 'investor-play',
    tags: ['tam','math','credibility','bottom-up'],
    bestFor: { industries:['SaaS','Enterprise','Fintech'], stages:['Series A','Series B+'], audiences:['Series A','Strategic'] },
    pairsWith: ['logos','value-selling','meddic'],
    swapAlternatives: ['power-law','anchoring'],
    risk: 'low',
  },
  {
    id: 'batna', name: 'BATNA Framing',
    summary: 'Quietly establish your best alternative — and make sure they know you have one.',
    steps: ['Our BATNA','Their BATNA','Mutual gain','Walk-away line'],
    when: 'Term-sheet and partnership negotiations.',
    tier: 'edgy', category: 'investor-play',
    tags: ['negotiation','leverage','alternative','walkaway'],
    bestFor: { industries: ALL_INDUSTRIES, stages:['Series A','Series B+'], audiences:['Series A','Strategic'] },
    pairsWith: ['door-in-the-face','anchoring','scarcity'],
    swapAlternatives: ['term-sheet-anchor','fomo'],
    risk: 'medium',
  },
  {
    id: 'bracketing', name: 'Bracketing',
    summary: 'Offer a range that brackets the number you actually want.',
    steps: ['Floor','Ceiling','True target','Land'],
    when: 'Round size, valuation, and pricing negotiations.',
    tier: 'edgy', category: 'investor-play',
    tags: ['negotiation','range','anchor','pricing'],
    bestFor: { industries: ALL_INDUSTRIES, stages:['Seed','Series A'], audiences:['Seed VC','Series A'] },
    pairsWith: ['anchoring','decoy','batna'],
    swapAlternatives: ['door-in-the-face','term-sheet-anchor'],
    risk: 'medium',
  },
]
